package com.ficsitcraft.client.building;

import com.ficsitcraft.FicsitCraft;
import com.ficsitcraft.block.PowerPoleBlock;
import com.ficsitcraft.multiblock.Footprint;
import com.ficsitcraft.multiblock.Multiblocks;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import net.minecraft.block.Block;
import net.minecraft.registry.Registries;
import net.minecraft.util.Identifier;
import org.jetbrains.annotations.Nullable;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Box models of every multi-block building. The geometry lives in {@code assets/ficsitcraft/buildings/<id>.json},
 * generated by {@code tools/gen_buildings.py} together with the per-building textures and the 3D item models,
 * so the placed building, its hologram and its inventory icon always match.
 */
public final class BuildingModels {
	private static final Map<Block, BuildingModel> MODELS = new HashMap<>();
	private static final String[] FACES = {"down", "up", "front", "back", "left", "right"};
	private static final String[] BUILDINGS = {
			"smelter", "constructor", "assembler", "foundry", "manufacturer", "miner_mk1", "miner_mk2",
			"biomass_burner", "coal_generator", "water_extractor", "fluid_buffer", "hub", "craft_bench", "storage_container",
			"creative_generator",
			"train_station", "freight_platform", "fluid_freight_platform", "empty_platform"
	};

	private BuildingModels() {
	}

	@Nullable
	public static BuildingModel get(Block block) {
		return MODELS.get(block);
	}

	public static void init() {
		if (!MODELS.isEmpty()) return;
		for (String name : BUILDINGS) {
			Block block = Registries.BLOCK.get(FicsitCraft.id(name));
			Footprint fp = Multiblocks.get(block);
			if (fp == null) {
				FicsitCraft.LOGGER.warn("No footprint registered for building {}", name);
				continue;
			}
			try {
				MODELS.put(block, load("buildings", name, fp));
			} catch (Exception e) {
				FicsitCraft.LOGGER.error("Failed to load building model {}", name, e);
			}
		}
	}

	private static final Map<String, BuildingModel> LOCAL = new HashMap<>();

	/** Rolling stock / trackside models (assets/ficsitcraft/vehicles/&lt;name&gt;.json), drawn in their own local frame. */
	@Nullable
	public static BuildingModel local(String name) {
		return LOCAL.computeIfAbsent(name, n -> {
			try {
				return load("vehicles", n, new Footprint(1, 1, 1, 0, 0));
			} catch (Exception e) {
				FicsitCraft.LOGGER.error("Failed to load model {}", n, e);
				return null;
			}
		});
	}

	private static BuildingModel load(String dir, String name, Footprint fp) throws Exception {
		String path = "/assets/" + FicsitCraft.MOD_ID + "/" + dir + "/" + name + ".json";
		try (InputStream in = BuildingModels.class.getResourceAsStream(path)) {
			if (in == null) throw new IllegalStateException("Missing " + path);
			JsonObject root = JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8)).getAsJsonObject();
			List<BuildingModel.Part> parts = new ArrayList<>();
			for (JsonElement el : root.getAsJsonArray("parts")) {
				JsonObject p = el.getAsJsonObject();
				JsonArray from = p.getAsJsonArray("from");
				JsonArray to = p.getAsJsonArray("to");
				Identifier[] tex = faces(p.getAsJsonObject("tex"), true);
				Identifier[] active = p.has("active") ? faces(p.getAsJsonObject("active"), false) : new Identifier[6];
				int flags = BuildingModel.STRETCH;
				if (p.has("flags")) {
					for (JsonElement fl : p.getAsJsonArray("flags")) {
						switch (fl.getAsString()) {
							case "glow" -> flags |= BuildingModel.GLOW_WHEN_ACTIVE;
							case "spin" -> flags |= BuildingModel.SPIN_WHEN_ACTIVE;
							case "alwaysGlow" -> flags |= BuildingModel.ALWAYS_GLOW;
							case "wheel" -> flags |= BuildingModel.WHEEL;
							default -> FicsitCraft.LOGGER.warn("Unknown part flag {} in {}", fl.getAsString(), name);
						}
					}
				}
				int tint = p.has("tint") ? p.get("tint").getAsInt() : 0xFFFFFF;
				parts.add(new BuildingModel.Part(
						from.get(0).getAsFloat(), from.get(1).getAsFloat(), from.get(2).getAsFloat(),
						to.get(0).getAsFloat(), to.get(1).getAsFloat(), to.get(2).getAsFloat(),
						tex, active, flags, tint));
			}
			return BuildingModel.of(fp, withWheelPivots(parts));
		}
	}

	/**
	 * The boxes of one wheel (same x range and same centre z) form a stepped octagon; its axle is the middle of their
	 * combined height, the radius half of it.
	 */
	private static List<BuildingModel.Part> withWheelPivots(List<BuildingModel.Part> parts) {
		Map<String, float[]> extent = new HashMap<>();
		for (BuildingModel.Part p : parts) {
			if ((p.flags() & BuildingModel.WHEEL) == 0) continue;
			float[] e = extent.computeIfAbsent(wheelKey(p), k -> new float[]{Float.MAX_VALUE, -Float.MAX_VALUE});
			e[0] = Math.min(e[0], p.y0());
			e[1] = Math.max(e[1], p.y1());
		}
		List<BuildingModel.Part> out = new ArrayList<>();
		for (BuildingModel.Part p : parts) {
			if ((p.flags() & BuildingModel.WHEEL) == 0) {
				out.add(p);
				continue;
			}
			float[] e = extent.get(wheelKey(p));
			float[] pivot = {(e[0] + e[1]) / 2f, (p.z0() + p.z1()) / 2f, (e[1] - e[0]) / 2f};
			out.add(new BuildingModel.Part(p.x0(), p.y0(), p.z0(), p.x1(), p.y1(), p.z1(), p.tex(), p.activeTex(), p.flags(), p.tint(), pivot));
		}
		return out;
	}

	private static String wheelKey(BuildingModel.Part p) {
		return Math.round(p.x0() * 1000) + "/" + Math.round(p.x1() * 1000) + "/" + Math.round((p.z0() + p.z1()) * 500);
	}


	private static Identifier[] faces(JsonObject obj, boolean fillMissing) {
		Identifier[] out = new Identifier[6];
		for (int i = 0; i < 6; i++) {
			if (obj != null && obj.has(FACES[i])) out[i] = BuildingModel.tex(obj.get(FACES[i]).getAsString());
			else if (fillMissing) out[i] = BuildingModel.tex("casing");
		}
		return out;
	}

	/** Simple model of a tall power pole, only used for the placement hologram. */
	public static BuildingModel pole(PowerPoleBlock pole) {
		int h = pole.getHeight();
		return BuildingModel.builder(new Footprint(1, 1, h, 0, 0))
				.box(0.25, 0, 0.25, 0.75, 0.2, 0.75).all("power_pole_mk" + pole.getMk()).done()
				.box(0.375, 0, 0.375, 0.625, h - 0.2, 0.625).all("power_pole_mk" + pole.getMk()).done()
				.box(0.06, h - 0.4, 0.4, 0.94, h - 0.2, 0.6).all("power_pole_mk" + pole.getMk()).done()
				.box(0.1, h - 0.2, 0.44, 0.22, h, 0.56).all("power_pole_insulator").done()
				.box(0.78, h - 0.2, 0.44, 0.9, h, 0.56).all("power_pole_insulator").done()
				.build();
	}
}
