#!/usr/bin/env python3
"""
FICSIT Craft train-system art pipeline.  Run from the project root AFTER gen_json.py and gen_buildings.py:

    python3 tools/gen_trains.py

Writes (and only these; nothing generated by another script is touched or deleted):
  * textures/block/trn/**                      every texture below (this directory is wiped and rebuilt on each run)
  * buildings/{train_station,freight_platform,fluid_freight_platform,empty_platform}.json   multi-block buildings
  * vehicles/{locomotive,freight_car,fluid_freight_car}.json                                rolling stock
  * vehicles/{signal_block,signal_path,switch_stand,switch_lever}.json                      trackside models
  * models/item/<all of the above except switch_*>.json  (3D miniatures; signals are rail_signal_block/_path)
  * textures/block/trn/{signal_lamp_*,track_*}.png + textures/item/railway.png + models/item/railway.json

It reuses the per-face painter (bldart.py) and the Building box DSL (gen_buildings.py) by import: every box face gets
its own texture, painted at the face's real size and stretched once over it.  Face texture orientation is the
game's (BuildingMesh.face): on `front` u runs toward -X, on `back` toward +X, on `left` from the front toward the
back, on `right` from the back toward the front, on `up`/`down` u runs toward +X with the top edge at the front.

Geometry conventions
  buildings : X = right (0..5), Y up, Z forward (0..9).  Track corridor x in [1.1, 3.9] is kept EMPTY above y = 0.4;
              a thin bed/sleepers/rails strip (rail head top y = 0.35) is drawn inside it (set TRACK_STRIP = False to omit).
  vehicles  : X in [0, 3] (centre 1.5), Z in [0, L] with the front at z = L, y = 0 is the rail head top.
"""
import hashlib
import json
import math
import os
import shutil
import sys
import zlib

TOOLS = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, TOOLS)
from bldart import *  # noqa: E402,F401,F403
import bldart  # noqa: E402
import gen_buildings as gb  # noqa: E402
from gen_buildings import (Building, OR, WH, GN, DK, ST, YL, FLOOR, HAZ, GRATE, UNDER, STRUT, STRUT_PLAIN,  # noqa: E402
                           FACES, connector, _container_doors)

PROJECT = os.path.abspath(os.path.join(TOOLS, '..'))
ROOT = os.path.join(PROJECT, 'src', 'main', 'resources', 'assets', 'ficsitcraft')
TRN = os.path.join(ROOT, 'textures', 'block', 'trn')
GEO_B = os.path.join(ROOT, 'buildings')
GEO_V = os.path.join(ROOT, 'vehicles')
ITEM_MODELS = os.path.join(ROOT, 'models', 'item')
ITEM_TEX = os.path.join(ROOT, 'textures', 'item')
TID = 'ficsitcraft:block/trn/'

TRACK_STRIP = True          # draw the thin bed/sleepers/rails inside the corridor of the four platform buildings
W_B = 5.0                   # building width
D_B = 9.0                   # building length
RAIL_TOP = 0.35             # rail head top in building space
DECK = 0.6                  # platform deck top

WRITTEN = []                # (path, note) for the final summary


def relp(p):
    return os.path.relpath(p, PROJECT)


# ------------------------------------------------------------------------------------------------------------------
# infrastructure: store, shared textures, coordinate maps
# ------------------------------------------------------------------------------------------------------------------
class TStore(Store):
    """Same as bldart.Store but with the `trn` texture namespace."""

    def save(self, img, name):
        h = hashlib.sha1(img.tobytes() + bytes(str(img.size), 'ascii')).hexdigest()
        if h in self.seen:
            return self.seen[h]
        name = name.lower()  # resource identifiers must be [a-z0-9/._-]; uppercase makes the whole model fail to load
        path = os.path.join(self.root, name + '.png')
        os.makedirs(os.path.dirname(path), exist_ok=True)
        img.save(path)
        rid = TID + name.replace(os.sep, '/')
        self.seen[h] = rid
        self.count += 1
        return rid


class Shared:
    """Pre-painted textures reused by many boxes (wheels, sleepers, rails ...): painted once, referenced by id."""

    def __init__(self, store):
        self.store = store
        self.cache = {}

    def get(self, key, spec, w, h, face='front'):
        if key not in self.cache:
            img = spec.paint(w, h, face, zlib.crc32(('trn-shared/' + key).encode()))
            self.cache[key] = self.store.save(img, 'shared/' + key)
        return self.cache[key]

    def img(self, key, img):
        if key not in self.cache:
            self.cache[key] = self.store.save(img, 'shared/' + key)
        return self.cache[key]


def coords(cv, face, box):
    """World (X, Y, Z) of every pixel centre of `face` of the box (x0,y0,z0,x1,y1,z1), following the game's UVs."""
    x0, y0, z0, x1, y1, z1 = box
    U = ((np.arange(cv.W) + 0.5) / cv.W)[None, :]
    V = ((np.arange(cv.H) + 0.5) / cv.H)[:, None]
    full = lambda a: np.broadcast_to(np.float32(a), (cv.H, cv.W))
    b = lambda a: np.broadcast_to(a.astype(np.float32), (cv.H, cv.W))
    if face == 'front':
        return b(x1 - U * (x1 - x0)), b(y1 - V * (y1 - y0)), full(z1)
    if face == 'back':
        return b(x0 + U * (x1 - x0)), b(y1 - V * (y1 - y0)), full(z0)
    if face == 'left':
        return full(x0), b(y1 - V * (y1 - y0)), b(z1 - U * (z1 - z0))
    if face == 'right':
        return full(x1), b(y1 - V * (y1 - y0)), b(z0 + U * (z1 - z0))
    if face == 'up':
        return b(x0 + U * (x1 - x0)), full(y1), b(z1 - V * (z1 - z0))
    return b(x0 + U * (x1 - x0)), full(y0), b(z1 - V * (z1 - z0))


def zu(face, t):
    """u fraction of a feature that sits at fraction t from the FRONT of a side face (left: u runs front->back)."""
    return t if face == 'left' else 1.0 - t


def save_png(img, path, note):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    img.save(path)
    WRITTEN.append((relp(path), note))


def write_json(path, obj, note, indent=1):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        json.dump(obj, f, indent=indent)
    WRITTEN.append((relp(path), note))


class TB(Building):
    """Building box DSL bound to the trn texture namespace, with geometry going to buildings/ or vehicles/."""

    def __init__(self, store, name, w, d, h, ax, az, kind='buildings', geo_name=None):
        super().__init__(store, name, w, d, h, ax, az)
        self.kind = kind
        self.geo_name = geo_name or name
        self.particle = None
        self.shared = None

    def box(self, x0, y0, z0, x1, y1, z1, all=None, flags=(), tint=None, active=None, share=None, **faces):
        """Like Building.box.  `down` defaults to the shared dark underside.  `share='key'` paints each face once per
        (key, face) and re-uses it for every later box with that key (posts, bollards, wheels ... equal small parts)."""
        x0, y0, z0, x1, y1, z1 = [round(v, 4) for v in (x0, y0, z0, x1, y1, z1)]
        if 'down' not in faces:
            faces['down'] = DOWN_ID[0]
        if share is not None:
            dims = {'front': (x1 - x0, y1 - y0), 'back': (x1 - x0, y1 - y0), 'left': (z1 - z0, y1 - y0),
                    'right': (z1 - z0, y1 - y0), 'up': (x1 - x0, z1 - z0), 'down': (x1 - x0, z1 - z0)}
            side = faces.pop('sides', None)
            spec = {f: all for f in FACES}
            if side is not None:
                for f in ('front', 'back', 'left', 'right'):
                    spec[f] = side
            spec.update(faces)
            faces = {}
            for f in FACES:
                fs = spec[f]
                if fs is None:
                    fs = GN()
                if isinstance(fs, F):
                    fs = self.shared.get('%s/%s' % (share, f), fs, dims[f][0], dims[f][1], f)
                faces[f] = fs
            if active:
                active = {f: (self.shared.get('%s/%s_on' % (share, f), fs, dims[f][0], dims[f][1], f)
                              if isinstance(fs, F) else fs) for f, fs in active.items()}
            all = None
        return super().box(x0, y0, z0, x1, y1, z1, all=all, flags=flags, tint=tint, active=active, **faces)

    def export(self):
        geo = GEO_B if self.kind == 'buildings' else GEO_V
        if self.kind == 'buildings':
            validate(self)
        ids = set()
        for p in self.parts:
            ids |= set(p['tex'].values())
            ids |= set(p.get('active', {}).values())
        write_json(os.path.join(geo, self.geo_name + '.json'),
                   {'footprint': [self.w, self.d, self.h, self.ax, self.az], 'parts': self.parts},
                   '%s geometry: %d boxes, %d distinct textures' % (self.kind[:-1], len(self.parts), len(ids)))
        if self.item:
            gb.ITEM_MODELS = ITEM_MODELS
            self.export_item_model()
            p = os.path.join(ITEM_MODELS, self.name + '.json')
            with open(p) as f:
                m = json.load(f)
            if self.particle:
                m['textures']['particle'] = self.particle
            with open(p, 'w') as f:
                json.dump(m, f, indent=1)
            WRITTEN.append((relp(p), '3D item miniature (%d elements)' % len(m['elements'])))

    item = True


DOWN_ID = [None]      # shared dark underside texture id (set in main)
INSULATOR_ID = 'ficsitcraft:block/power_pole_insulator'


# ------------------------------------------------------------------------------------------------------------------
# generic painters built on world coordinates
# ------------------------------------------------------------------------------------------------------------------
LIGHT3 = np.array([-0.35, 0.85, 0.35], np.float32)
LIGHT3 /= np.linalg.norm(LIGHT3)
HALF3 = LIGHT3 + np.array([0, 0.3, 1.0], np.float32)
HALF3 /= np.linalg.norm(HALF3)


def shade_normal(nx, ny, nz, spec=0.25, base=0.52, gain=0.62):
    d = np.clip(nx * LIGHT3[0] + ny * LIGHT3[1] + nz * LIGHT3[2], 0, 1)
    h = np.clip(nx * HALF3[0] + ny * HALF3[1] + nz * HALF3[2], 0, 1)
    return base + gain * d + spec * h ** 24


def tube_base(box, axis, c0, c1, R, color, bands=(), seams=(), soot=0.0, rings_every=None, cap_style='plain',
              seam_col=None, kind='metal'):
    """Base painter for a face of an axis-aligned cylinder approximated by stacked boxes.

    axis 'z': c0 = centre x, c1 = centre y (axis along z);  'x': c0 = centre z, c1 = centre y;  'y': c0 = centre x, c1 = centre z.
    bands: (along0, along1, colour);  seams: along positions of weld seams.
    """

    def fn(cv):
        X, Y, Z = coords(cv, cv.face, box)
        if axis == 'z':
            a, b, al = X - c0, Y - c1, Z
        elif axis == 'x':
            a, b, al = Z - c0, Y - c1, X
        else:
            a, b, al = X - c0, Z - c1, Y
        r = np.hypot(a, b)
        face_along = {'z': ('left', 'right', 'up', 'down'), 'x': ('front', 'back', 'up', 'down'),
                      'y': ('front', 'back', 'left', 'right')}[axis]
        if cv.face in face_along:
            rr = np.maximum(r, 1e-6)
            na, nb = a / rr, b / rr
            if axis == 'z':
                sh = shade_normal(na, nb, 0.0)
            elif axis == 'x':
                sh = shade_normal(0.0, nb, na)
            else:
                sh = shade_normal(na, 0.0, nb)
            col = np.zeros((cv.H, cv.W, 3), np.float32) + np.asarray(color, np.float32)
            for (z0, z1, c) in bands:
                m = (al >= z0) & (al < z1)
                col[m] = c
            cv.a[:] = col * sh[..., None]
            for s in seams:
                m = np.abs(al - s) < 0.5 / cv.sx if cv.side else np.abs(al - s) < 0.5 / cv.sy
                m = np.abs(al - s) < 0.022
                cv.a[m] *= 0.62
                m2 = (al - s >= 0.022) & (al - s < 0.05)
                cv.a[m2] *= 1.18
            if soot:
                v = np.clip((b + R) / (2 * R), 0, 1)
                s = np.clip(1 - v * 1.5, 0, 1) * soot
                cv.a *= (1 - 0.55 * s)[..., None]
            return kind
        # end cap: spherical shading, weld rings
        rn = np.clip(r / R, 0, 1.2)
        nz = np.sqrt(np.clip(1 - rn ** 2, 0, 1))
        sgn = {'front': 1, 'back': -1, 'right': 1, 'left': -1, 'up': 1, 'down': -1}[cv.face]
        an, bn = a / R, b / R
        if axis == 'z':
            sh = shade_normal(an, bn, nz * sgn)
        elif axis == 'x':
            sh = shade_normal(nz * sgn, bn, an)
        else:
            sh = shade_normal(an, nz * sgn, bn)
        cv.a[:] = np.asarray(color, np.float32) * sh[..., None] * 0.92
        for rr_, dark in ((0.93, 0.6), (0.62, 0.7)):
            m = np.abs(rn - rr_) < 0.03
            cv.a[m] *= dark
        if cap_style == 'manway':
            m = rn < 0.22
            cv.a[m] = np.asarray(STEEL_D, np.float32) * sh[m][:, None]
            m = np.abs(rn - 0.22) < 0.03
            cv.a[m] *= 0.5
        elif cap_style == 'vent':
            cv.a[rn < 0.5] = BLACK
        elif cap_style == 'glowhole':
            cv.a[rn < 0.5] = C('#2A1208')
        elif cap_style == 'pipe':
            # open pipe mouth: dark bore, bright blue lip, bolted flange
            cv.a[rn < 0.56] = C('#07131B')
            cv.a[(rn >= 0.56) & (rn < 0.66)] = BLUE * sh[(rn >= 0.56) & (rn < 0.66)][:, None]
            cv.a[(rn >= 0.4) & (rn < 0.56)] *= 0.75
            for k in range(8):
                ang = k * math.pi / 4 + 0.2
                bx, by = an * 0 + math.cos(ang) * 0.82, bn * 0 + math.sin(ang) * 0.82
                m = np.hypot(an - bx, bn - by) < 0.075
                cv.a[m] = STEEL_L * 0.9
        return kind

    return fn


def wheel_face(box, cx, cy, cz, R, hub=0.14):
    """Locomotive wheel: steel disc with rim, spokes and hub; box faces slice it (coordinates relative to the centre)."""

    def fn(cv):
        X, Y, Z = coords(cv, cv.face, box)
        r = np.hypot(Z - cz, Y - cy) / R
        ang = np.arctan2(Y - cy, Z - cz)
        if cv.face in ('left', 'right'):
            cv.a[:] = STEEL_D * 1.05
            web = (r > 0.3) & (r <= 0.72)
            spokes = web & (np.abs(np.sin(ang * 3)) > 0.8)
            cv.a[web] = GUN * 1.05
            cv.a[spokes] = STEEL * 0.95
            cv.a[(r > 0.72) & (r <= 0.84)] = STEEL_D * 0.9
            cv.a[(r > 0.84) & (r <= 0.96)] = STEEL * 1.0
            cv.a[(r > 0.96)] = GUN * 0.8
            cv.a[(np.abs(r - 0.72) < 0.03)] *= 0.55
            cv.a[r < 0.3] = STEEL * 0.9
            cv.a[r < 0.2] = ORANGE_D
            cv.a[r < 0.1] = BLACK
            sh = 1 + 0.25 * np.cos(ang - 2.3) * (r > 0.84)
            cv.a *= sh[..., None]
        else:
            cv.a[:] = STEEL * 0.78
            cv.a *= (0.85 + 0.15 * np.sin((Z + Y) * 40))[..., None]
        return 'metal'

    return fn


def dot_grid(cv, x0, y0, x1, y1, step, c, r=1):
    for y in range(y0, y1, step):
        for x in range(x0, x1, step):
            cv.rect(x, y, x + r, y + r, c)


# ------------------------------------------------------------------------------------------------------------------
# C) signal lamp textures   (16x16 glossy round lamps on a dark square)
# ------------------------------------------------------------------------------------------------------------------
def lamp_image(core, mid, edge, glow_a=0.0, off=False):
    n = 16
    yy, xx = np.mgrid[0:n, 0:n]
    cx = cy = (n - 1) / 2
    d = np.hypot(xx - cx, yy - cy)
    img = np.zeros((n, n, 4), np.float32)
    img[..., :3] = C('#15171B')
    img[..., 3] = 255
    # faint bevel of the dark square housing
    img[0, :, :3] *= 1.5
    img[:, 0, :3] *= 1.3
    img[-1, :, :3] *= 0.6
    img[:, -1, :3] *= 0.7
    # bezel ring
    ring = (d > 6.2) & (d <= 7.4)
    img[ring, :3] = C('#2F3339')
    img[(d > 7.0) & (d <= 7.6), :3] = C('#0B0C0E')
    lens = d <= 6.2
    t = np.clip(d / 6.2, 0, 1)
    core, mid, edge = np.asarray(core, np.float32), np.asarray(mid, np.float32), np.asarray(edge, np.float32)
    col = np.where((t < 0.55)[..., None], core + (mid - core) * (t / 0.55)[..., None],
                   mid + (edge - mid) * ((t - 0.55) / 0.45)[..., None])
    # glossy off-centre highlight (upper left)
    hl = np.exp(-(((xx - 5.2) ** 2 + (yy - 5.0) ** 2) / 3.0))
    col = col + (255 - col) * (0.55 * hl)[..., None] * (0.5 if off else 1.0)
    img[lens, :3] = col[lens]
    # lens rim darkening
    rim = (d > 5.3) & (d <= 6.2)
    img[rim, :3] *= 0.78
    # tiny cross-light streak on the lower right
    st = (d < 5.6) & (xx + yy > 19)
    img[st, :3] = np.minimum(img[st, :3] * 1.08, 255)
    return Image.fromarray(np.clip(img, 0, 255).astype(np.uint8), 'RGBA')


def gen_lamps():
    red = lamp_image(C('#FFB4A6'), C('#F03A2C'), C('#8C0E10'))
    green = lamp_image(C('#D8FFD0'), C('#38D24A'), C('#0C6A22'))
    off = lamp_image(C('#5C6068'), C('#33363D'), C('#1C1E22'), off=True)
    for n, im in (('signal_lamp_red', red), ('signal_lamp_green', green), ('signal_lamp_off', off)):
        save_png(im, os.path.join(TRN, n + '.png'), 'signal lamp 16x16')


# ------------------------------------------------------------------------------------------------------------------
# D) track textures (seamless 32x32)
# ------------------------------------------------------------------------------------------------------------------
def _wrap_blur(a, k=1):
    out = a.copy()
    for _ in range(k):
        out = (out * 4 + np.roll(out, 1, 0) + np.roll(out, -1, 0) + np.roll(out, 1, 1) + np.roll(out, -1, 1)) / 8
    return out


def tile_noise(rng, n, cells, octaves=1):
    """Periodic value noise (seamless when tiled)."""
    out = np.zeros((n, n), np.float32)
    amp, tot = 1.0, 0.0
    for o in range(octaves):
        c = cells * (2 ** o)
        g = rng.uniform(-1, 1, (c, c)).astype(np.float32)
        gi = np.zeros((n, n), np.float32)
        xs = (np.arange(n) + 0.5) / n * c
        ys = (np.arange(n) + 0.5) / n * c
        x0 = np.floor(xs).astype(int) % c
        x1 = (x0 + 1) % c
        y0 = np.floor(ys).astype(int) % c
        y1 = (y0 + 1) % c
        fx = (xs - np.floor(xs))
        fy = (ys - np.floor(ys))
        fx = fx * fx * (3 - 2 * fx)
        fy = fy * fy * (3 - 2 * fy)
        top = g[np.ix_(y0, x0)] * (1 - fx)[None, :] + g[np.ix_(y0, x1)] * fx[None, :]
        bot = g[np.ix_(y1, x0)] * (1 - fx)[None, :] + g[np.ix_(y1, x1)] * fx[None, :]
        gi = top * (1 - fy)[:, None] + bot * fy[:, None]
        out += gi * amp
        tot += amp
        amp *= 0.5
    return out / tot


def ballast_array(n=32, seed=101):
    """Seamless crushed-stone tile (float RGB): angular, faceted stones of mixed greys over dark gaps."""
    rng = np.random.default_rng(seed)
    img = np.zeros((n, n, 3), np.float32)
    img[:] = C('#3A3D41')                                 # dark gaps between stones
    img += 7 * tile_noise(rng, n, 4)[..., None]
    yy, xx = np.mgrid[0:n, 0:n].astype(np.float32)
    stones = []
    for i in range(105):
        stones.append((rng.uniform(0, n), rng.uniform(0, n), rng.uniform(1.5, 2.9), rng.uniform(0.7, 1.0),
                       rng.uniform(0, math.pi), rng.uniform(0.55, 0.85), rng.uniform(0, 2 * math.pi), rng.uniform(-1, 1)))
    stones.sort(key=lambda s_: s_[5])
    tints = (C('#9A9DA1'), C('#8A8D92'), C('#A29F98'), C('#7C8085'), C('#9C9C99'))
    for k, (sx, sy, sr, asp, th, tone, fa, tint) in enumerate(stones):
        base = tints[k % len(tints)] * tone
        for ox in (-n, 0, n):
            for oy in (-n, 0, n):
                cx, cy = sx + ox, sy + oy
                if cx < -5 or cx > n + 5 or cy < -5 or cy > n + 5:
                    continue
                dx, dy = xx + 0.5 - cx, yy + 0.5 - cy
                c, s_ = math.cos(th), math.sin(th)
                u, v = dx * c + dy * s_, (-dx * s_ + dy * c) / asp
                d = (np.abs(u / sr) ** 2.7 + np.abs(v / sr) ** 2.7) ** (1 / 2.7)      # squarish, angular outline
                m = d < 1.0
                if not m.any():
                    continue
                # two flat facets split by a random line through the stone + a soft top-left light
                side = (dx * math.cos(fa) + dy * math.sin(fa)) / sr
                facet = np.where(side > 0.15, 0.86, np.where(side < -0.25, 1.08, 1.0))
                light = 1.08 - 0.22 * ((dx + dy) / (2 * sr))
                shade = np.clip(facet * light - 0.2 * d ** 4, 0.35, 1.25)
                col = base[None, None, :] * shade[..., None]
                img[m] = col[m]
                edge = m & (d > 0.88)
                img[edge] *= 0.7
    # concrete dust settling between stones + warm grit
    dust = np.clip(tile_noise(rng, n, 8, 2) * 0.6 + 0.25, 0, 1)
    img = img * (1 - 0.18 * dust[..., None]) + C('#A8A296') * 0.18 * dust[..., None]
    img *= (1 + 0.06 * rng.uniform(-1, 1, (n, n, 1)))
    return img


def sleeper_array(n=32, seed=202, plates=True):
    """Seamless creosote-timber tile, grain along x (float RGB); optionally with tie plates + lag screws."""
    rng = np.random.default_rng(seed)
    yy, xx = np.mgrid[0:n, 0:n].astype(np.float32)
    base = C('#3B2C22')
    grain = tile_noise(rng, n, 2, 2)
    fine = np.sin((yy + 3 * tile_noise(rng, n, 4)) * 2 * math.pi / 32 * 5)
    img = np.zeros((n, n, 3), np.float32) + base
    img *= (1 + 0.18 * grain + 0.07 * fine)[..., None]
    for y in (0, 15, 16):
        img[y % n, :, :] *= 0.72 if y == 0 else 0.9
    for _ in range(9):
        x, y = rng.integers(0, n), rng.integers(1, n - 1)
        ln = rng.integers(3, 8)
        for i in range(ln):
            img[y, (x + i) % n] *= 0.6
    sheen = np.clip(tile_noise(rng, n, 3) - 0.35, 0, 1)
    img = img + sheen[..., None] * 18
    if plates:
        for (px, py) in ((7, 8), (7, 23), (24, 8), (24, 23)):
            img[py - 1:py + 2, px - 1:px + 2] = C('#5A5F66')
            img[py, px] = C('#A0A6AD')
            img[py + 1, px + 1] = C('#2A2D31')
            img[py + 1, px] = C('#3B3F45')
        for (px, py) in ((7, 8), (7, 23), (24, 8), (24, 23)):
            img[py - 3:py - 2, px - 2:px + 3] = C('#26282C')
            img[py + 3:py + 4, px - 2:px + 3] = C('#26282C')
    img *= (1 + 0.03 * rng.uniform(-1, 1, (n, n, 1)))
    return img


def _rgba(img):
    a = np.full(img.shape[:2] + (1,), 255, np.float32)
    return Image.fromarray(np.clip(np.concatenate([img, a], 2), 0, 255).astype(np.uint8), 'RGBA')


def gen_track_ballast():
    save_png(_rgba(ballast_array()), os.path.join(TRN, 'track_ballast.png'), 'seamless 32x32 crushed-stone ballast')


def gen_track_sleeper():
    save_png(_rgba(sleeper_array()), os.path.join(TRN, 'track_sleeper.png'), 'seamless 32x32 creosote sleeper with lag screws')


def gen_track_rail():
    n = 32
    rng = np.random.default_rng(303)
    yy, xx = np.mgrid[0:n, 0:n].astype(np.float32)
    v = (yy + 0.5) / n
    prof = np.abs(v - 0.5) * 2                           # 0 at the centre line, 1 at the edges (symmetric -> wrap safe)
    img = np.zeros((n, n, 3), np.float32)
    steel = C('#7C838B')
    img[:] = steel
    # rounded head: darker toward the flanks, worn bright band on top
    img *= (0.62 + 0.55 * (1 - prof ** 1.6))[..., None]
    band = np.clip(1 - (prof / 0.42) ** 2, 0, 1)
    wear = C('#E6EAEE') * (0.9 + 0.1 * tile_noise(rng, n, 4))[..., None]
    img = img * (1 - 0.85 * band[..., None] ** 0.8) + wear * (0.85 * band[..., None] ** 0.8)
    # rolling marks + rust bloom on the flanks
    rust = np.clip(tile_noise(rng, n, 5, 2) * 0.8, 0, 1) * np.clip((prof - 0.55) / 0.45, 0, 1)
    img = img * (1 - 0.45 * rust[..., None]) + C('#7A4A2A') * 0.45 * rust[..., None]
    streak = tile_noise(rng, n, 2, 1)
    img *= (1 + 0.05 * streak[..., None])
    # fine longitudinal polish lines
    for y in (11, 14, 17, 20):
        img[y] *= 1.06
    img *= (1 + 0.025 * rng.uniform(-1, 1, (n, n, 1)))
    a = np.full((n, n, 1), 255, np.float32)
    save_png(Image.fromarray(np.clip(np.concatenate([img, a], 2), 0, 255).astype(np.uint8), 'RGBA'),
             os.path.join(TRN, 'track_rail.png'), 'seamless 32x32 worn rail head (light strip along u)')


def gen_track_hologram():
    n = 16
    img = np.zeros((n, n, 4), np.uint8)
    img[:] = (255, 255, 255, 255)
    for i in (0, 8):
        img[i, :, :3] = (222, 236, 246)
        img[:, i, :3] = (222, 236, 246)
    img[0, 0, :3] = (205, 224, 240)
    img[0, 8, :3] = img[8, 0, :3] = img[8, 8, :3] = (205, 224, 240)
    save_png(Image.fromarray(img, 'RGBA'), os.path.join(TRN, 'track_hologram.png'), '16x16 white hologram tile, faint grid')


# ------------------------------------------------------------------------------------------------------------------
# E) 2D item icon  (16x16 curved steel track piece)
# ------------------------------------------------------------------------------------------------------------------
def gen_railway_icon():
    """Curved steel track piece: two rails bent through a quarter turn, tied together by wooden sleepers.
    Drawn 8x oversampled and snapped to a 16x16 palette so the shapes stay clean pixel art."""
    n, ss = 16, 8
    cx, cy = 16.9 * ss, 16.9 * ss            # centre of the bend (lower right)
    r_in, r_out = 8.3 * ss, 13.9 * ss        # rail centre lines
    HI, MID, LO = C('#EEF2F5'), C('#B2BAC2'), C('#6E777F')
    SLP, SLP_L, SLP_D = C('#8E5F37'), C('#B98652'), C('#54371F')
    from PIL import ImageDraw

    def layer():
        return Image.new('L', (n * ss, n * ss), 0)

    L = {k: layer() for k in ('slp', 'slp_l', 'slp_d', 'lo', 'mid', 'hi')}
    D = {k: ImageDraw.Draw(v) for k, v in L.items()}
    nk = 5
    for k in range(nk):
        a = math.pi + (math.pi / 2) * (k + 0.5) / nk
        c, s_ = math.cos(a), math.sin(a)
        r0, r1 = r_in - 1.6 * ss, r_out + 1.6 * ss
        p0 = (cx + c * r0, cy + s_ * r0)
        p1 = (cx + c * r1, cy + s_ * r1)
        D['slp'].line([p0, p1], fill=255, width=int(1.9 * ss))
        # lit upper-left edge and dark end grain
        t = (-s_, c)
        q0 = (p0[0] - t[0] * 0.8 * ss, p0[1] - t[1] * 0.8 * ss)
        q1 = (p1[0] - t[0] * 0.8 * ss, p1[1] - t[1] * 0.8 * ss)
        D['slp_l'].line([q0, q1], fill=255, width=int(0.9 * ss))
        D['slp_d'].line([(cx + c * r0, cy + s_ * r0), (cx + c * (r0 + 0.9 * ss), cy + s_ * (r0 + 0.9 * ss))], fill=255, width=int(2.3 * ss))
        D['slp_d'].line([(cx + c * (r1 - 0.9 * ss), cy + s_ * (r1 - 0.9 * ss)), (cx + c * r1, cy + s_ * r1)], fill=255, width=int(2.3 * ss))
    for rr in (r_in, r_out):
        for key, dr, w in (('lo', -0.55 * ss, 1.0 * ss), ('mid', 0.05 * ss, 0.9 * ss), ('hi', 0.65 * ss, 0.9 * ss)):
            r = rr + dr
            D[key].arc([cx - r, cy - r, cx + r, cy + r], 180, 270, fill=255, width=int(w))
    cov = {k: np.asarray(v, np.float32).reshape(n, ss, n, ss).mean(axis=(1, 3)) / 255 for k, v in L.items()}
    out = np.zeros((n, n, 4), np.uint8)
    for y in range(n):
        for x in range(n):
            col = None
            if cov['slp'][y, x] > 0.45:
                col = SLP
                if cov['slp_l'][y, x] > 0.45:
                    col = SLP_L
                if cov['slp_d'][y, x] > 0.5:
                    col = SLP_D
            for key, c in (('lo', LO), ('mid', MID), ('hi', HI)):
                if cov[key][y, x] > 0.5:
                    col = c
            if col is not None:
                out[y, x] = (*[int(v) for v in col], 255)
    # fill the enclosed gaps of the ladder with dark ballast so the piece reads as one solid object
    inside = np.zeros((n, n), bool)
    yy, xx = np.mgrid[0:n, 0:n]
    dd = np.hypot(xx + 0.5 - cx / ss, yy + 0.5 - cy / ss)
    aa = np.arctan2(yy + 0.5 - cy / ss, xx + 0.5 - cx / ss) % (2 * math.pi)
    bed = (aa >= math.pi - 0.02) & (aa <= 1.5 * math.pi + 0.02) & (dd >= r_in / ss - 1.6) & (dd <= r_out / ss + 1.6)
    for y in range(n):
        for x in range(n):
            if bed[y, x] and out[y, x, 3] == 0:
                out[y, x] = (0x4A, 0x4E, 0x55, 255) if (x + y) % 5 else (0x5A, 0x5F, 0x66, 255)
    src = out.copy()
    for y in range(n):
        for x in range(n):
            if src[y, x, 3] == 0:
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    nx, ny = x + dx, y + dy
                    if 0 <= nx < n and 0 <= ny < n and src[ny, nx, 3] > 0:
                        out[y, x] = (18, 20, 24, 255)
                        break
    save_png(Image.fromarray(out, 'RGBA'), os.path.join(ITEM_TEX, 'railway.png'), '16x16 item icon: curved steel track piece')
    write_json(os.path.join(ITEM_MODELS, 'railway.json'),
               {'parent': 'minecraft:item/generated', 'textures': {'layer0': 'ficsitcraft:item/railway'}},
               'item model for the Railway item', indent=2)


# ------------------------------------------------------------------------------------------------------------------
# materials + decals specific to the train system
# ------------------------------------------------------------------------------------------------------------------
CONC = C('#8B8F95')
CONC_D = C('#6D7178')


def concrete(color=CONC, seam=1.5, ties=True, stain=0.0):
    """Poured concrete: formwork panels, tie holes, aggregate speckle."""

    def fn(cv):
        cv.fill(color)
        n = cv.lownoise(0.7) * 0.06 + cv.lownoise(0.22) * 0.045
        cv.a *= (1 + n)[..., None]
        sp = cv.rng.uniform(0, 1, (cv.H, cv.W))
        cv.a[sp > 0.982] *= 1.22
        cv.a[sp < 0.02] *= 0.72
        if cv.fw > 0.9 and cv.fh > 0.5:
            nx = max(1, int(round(cv.fw / seam)))
            for i in range(1, nx):
                x = int(i * cv.W / nx)
                cv.mul(x, 0, x + 1, cv.H, 0.62)
                cv.mul(x + 1, 0, x + 2, cv.H, 1.12)
        if cv.fh > 0.9:
            ny = max(1, int(round(cv.fh / 1.2)))
            for i in range(1, ny):
                y = int(i * cv.H / ny)
                cv.mul(0, y, cv.W, y + 1, 0.66)
        if ties and cv.fw > 0.6 and cv.fh > 0.4:
            for y in range(int(0.22 * cv.sy), cv.H - 2, max(6, int(0.5 * cv.sy))):
                for x in range(int(0.25 * cv.sx), cv.W - 2, max(6, int(0.5 * cv.sx))):
                    cv.rect(x, y, x + 2, y + 2, color * 0.72)
                    cv.rect(x, y, x + 1, y + 1, color * 0.55)
        if stain:
            m = np.clip(cv.lownoise(0.5) * 0.9, 0, 1)
            cv.a *= (1 - stain * m)[..., None]
        return 'rough'

    return fn


def ballast_bed(shade=0.9):
    tile = ballast_array()

    def fn(cv):
        ry, rx = cv.H // 32 + 2, cv.W // 32 + 2
        big = np.tile(tile, (ry, rx, 1))[:cv.H, :cv.W]
        cv.a[:] = big * shade
        return 'rough'

    return fn


def timber(plate_u=()):
    tile = sleeper_array(plates=False)

    def fn(cv):
        ry, rx = cv.H // 32 + 2, cv.W // 32 + 2
        cv.a[:] = np.tile(tile, (ry, rx, 1))[:cv.H, :cv.W]
        for u in plate_u:
            cx = int(u * cv.W)
            y0, y1 = int(cv.H * 0.12), int(cv.H * 0.88)
            cv.rect(cx - 5, y0, cx + 5, y1, GUN * 0.9)
            cv.bevel(cx - 5, y0, cx + 5, y1)
            for yy in (y0 + 2, y1 - 3):
                for xx in (cx - 3, cx + 2):
                    rivet(cv, xx, yy, GUN)
        return 'rough'

    return fn


def rail_top():
    def fn(cv):
        t = np.broadcast_to(cv.ub() / cv.fw, (cv.H, cv.W))
        prof = np.abs(t - 0.5) * 2
        k = 0.62 + 0.4 * (1 - prof ** 1.6)
        cv.a[:] = STEEL[None, None, :] * k[..., None]
        band = np.clip(1 - (prof / 0.6) ** 2, 0, 1)[..., None]
        cv.a[:] = cv.a * (1 - 0.75 * band) + STEEL_L * 1.08 * (0.75 * band)
        cv.a *= (1 + 0.04 * cv.lownoise(0.5))[..., None]
        return 'metal'

    return fn


def rail_web(c=C('#5A5148')):
    def fn(cv):
        cv.fill(c)
        cv.a *= (1 + 0.15 * cv.lownoise(0.4))[..., None]
        for x in range(int(0.3 * cv.sx), cv.W, int(3.0 * cv.sx) or 1):
            cv.rect(x, 0, x + 3, cv.H, STEEL_D)
            cv.rect(x, 0, x + 1, cv.H, STEEL)
        return 'metal'

    return fn


def rect_line(X, Z, xa, xb, za, zb, t):
    """Mask of a rectangle outline of thickness t in (X, Z) world coordinates."""
    inside = (X >= xa) & (X < xb) & (Z >= za) & (Z < zb)
    inner = (X >= xa + t) & (X < xb - t) & (Z >= za + t) & (Z < zb - t)
    return inside & ~inner


def deck_marks(box, side, zones=(), studs=True, line=True, centre_line=None):
    """Deck top markings in world coordinates: tactile studs + safety line along the track edge, bay outlines."""

    def fn(cv):
        X, Y, Z = coords(cv, 'up', box)
        dist = (1.1 - X) if side == 'L' else (X - 3.9)
        if studs:
            dd = np.mod(dist - 0.12, 0.1) - 0.05
            zz = np.mod(Z, 0.1) - 0.05
            band = (dist >= 0.12) & (dist < 0.32)
            dot = band & (np.hypot(dd, zz) < 0.03)
            sh = 1.0 + 0.5 * (-(dd + zz) * 12)
            cv.a[dot] = YELLOW * np.clip(sh[dot], 0.7, 1.4)[:, None]
            cv.a[band & ~dot] *= 0.8
        if line:
            m = (dist >= 0.42) & (dist < 0.5)
            cv.a[m] = YELLOW
            cv.a[(dist >= 0.5) & (dist < 0.52)] *= 0.7
        for (za, zb, d0, d1, col) in zones:
            xa, xb = (1.1 - d1, 1.1 - d0) if side == 'L' else (3.9 + d0, 3.9 + d1)
            m = rect_line(X, Z, xa, xb, za, zb, 0.05)
            cv.a[m] = col
        if centre_line is not None:
            for zc in centre_line:
                m = (np.abs(Z - zc) < 0.03) & (dist > 0.55)
                cv.a[m] = YELLOW * 0.9

    return fn


def win(cx, cy, w, h, lit=True, tint=C('#4F86A8'), bars=1, seed=0):
    """Framed window: sky reflection above, a (warm, when lit) room interior with silhouettes below."""

    def fn(cv):
        ww, hh = min(w, cv.fw * 0.94), min(h, cv.fh * 0.94)
        x0, y0, x1, y1 = cv.px_rect(cx, cy, ww, hh)
        cv.rect(x0, y0, x1, y1, GUN)
        t = max(1, int(0.045 * cv.sx))
        ix0, iy0, ix1, iy1 = x0 + t, y0 + t, x1 - t, y1 - t
        if ix1 - ix0 < 3 or iy1 - iy0 < 3:
            return
        cv.vgrad(ix0, iy0, ix1, iy1, tint * (1.05 if lit else 0.8), tint * (0.42 if not lit else 0.5))
        if lit:
            g = np.zeros((cv.H, cv.W), np.float32)
            g[iy0 + (iy1 - iy0) // 3:iy1, ix0:ix1] = 1
            warm = C('#FFD48A')
            wob = (0.55 + 0.45 * cv.lownoise(0.2))
            k = (g * 0.5 * wob)[..., None]
            cv.a[:] = cv.a * (1 - k) + warm * k
            # silhouettes of people / fixtures
            rng = np.random.default_rng(seed + int(cx * 100))
            for _ in range(max(1, (ix1 - ix0) // 9)):
                sx = int(rng.uniform(ix0 + 2, ix1 - 4))
                hgt = int((iy1 - iy0) * rng.uniform(0.3, 0.5))
                cv.rect(sx, iy1 - hgt, sx + 2, iy1, DARK, 0.75)
                cv.rect(sx, iy1 - hgt - 2, sx + 2, iy1 - hgt, DARK, 0.75)
        # diagonal glare
        u = (np.arange(cv.W)[None, :] + np.arange(cv.H)[:, None] * 0.7)
        streak = (np.mod(u, 26) < 4) & (np.arange(cv.W)[None, :] >= ix0) & (np.arange(cv.W)[None, :] < ix1) \
            & (np.arange(cv.H)[:, None] >= iy0) & (np.arange(cv.H)[:, None] < iy1)
        cv.a[streak] = cv.a[streak] * 0.8 + 255 * 0.2
        for i in range(1, bars + 1):
            mx = ix0 + (ix1 - ix0) * i // (bars + 1)
            cv.rect(mx, iy0, mx + 1, iy1, GUN)
        cv.bevel(x0, y0, x1, y1)
        cv.clean[y0:y1, x0:x1] = 1

    return fn


def sliding_door(cx, w, h):
    """Bottom-aligned automatic double glass door: lit header, centre gap, push plates and a hazard sill."""

    def fn(cv):
        if not cv.fits(w, h, 1.0):
            return
        x0, _, x1, _ = cv.px_rect(cx, 0.5, w, h)
        y1 = cv.H - 1
        y0 = y1 - int(h * cv.sy)
        cv.rect(x0 - 2, y0 - 3, x1 + 2, y1, GUN)
        cv.rect(x0, y0, x1, y1, C('#173040'))
        mid = (x0 + x1) // 2
        for (a, b) in ((x0 + 1, mid - 1), (mid + 1, x1 - 1)):
            cv.vgrad(a, y0 + 1, b, y1 - 3, C('#5FA0C4'), C('#2A5670'))
            for k in range(0, (y1 - y0), 9):
                cv.rect(a, y0 + k, b, y0 + k + 2, (255, 255, 255), 0.12)
        cv.rect(mid - 1, y0, mid + 1, y1, BLACK)
        cv.rect(x0 - 2, y0 - 5, x1 + 2, y0 - 2, C('#EAB545'))
        cv.rect(mid - 2, (y0 + y1) // 2 - 3, mid - 1, (y0 + y1) // 2 + 3, STEEL_L)
        cv.rect(mid + 1, (y0 + y1) // 2 - 3, mid + 2, (y0 + y1) // 2 + 3, STEEL_L)
        u, v = cv.ub(), cv.vb()
        m = (np.floor((u + v) / 0.07) % 2 == 0)
        reg = np.zeros((cv.H, cv.W), bool)
        reg[y1 - max(2, int(0.06 * cv.sy)):y1, x0 - 2:x1 + 2] = True
        cv.a[:] = np.where((reg & m)[..., None], YELLOW, np.where(reg[..., None], BLACK * 1.0, cv.a))
        cv.clean[y0 - 5:y1, x0 - 2:x1 + 2] = 1

    return fn


def rungs(cx=0.5, w=0.7):
    """Ladder: two steel stiles and evenly spaced rungs on a dark backing."""

    def fn(cv):
        cv.fill(DARK)
        x0, x1 = int((cx - w / 2) * cv.W), int((cx + w / 2) * cv.W)
        st = max(1, int(0.05 * cv.sx))
        cv.rect(x0, 0, x0 + st, cv.H, STEEL)
        cv.rect(x1 - st, 0, x1, cv.H, STEEL)
        for y in range(2, cv.H, max(3, int(0.22 * cv.sy))):
            cv.rect(x0, y, x1, y + 1, STEEL_L)
            cv.rect(x0, y + 1, x1, y + 2, STEEL_D)
        cv.mul(x0, 0, x0 + 1, cv.H, 1.25)
        return 'metal'

    return fn


def lamp_face(col, on=True):
    """Lens of a lamp housing: glowing rectangle in a dark bezel."""

    def fn(cv):
        cv.fill(DARK)
        m = max(1, int(0.12 * min(cv.W, cv.H)))
        c = np.asarray(col, np.float32)
        cv.vgrad(m, m, cv.W - m, cv.H - m, c * (1.15 if on else 0.28), c * (0.8 if on else 0.16))
        cv.frame(0, 0, cv.W, cv.H, GUN, 1)
        cv.bevel(m, m, cv.W - m, cv.H - m, 1.2 if on else 1.05, 0.7)
        cv.clean[:] = 1 if on else 0
        return 'none' if on else 'metal'

    return fn


def dome_top(color=WHITE):
    return cylinder(color, 'y', rings=0)


# ------------------------------------------------------------------------------------------------------------------
# platform building helpers (decks, track strip, side-mirrored machinery)
# ------------------------------------------------------------------------------------------------------------------
def track_strip(b):
    """Thin ballast bed + sleepers + two rails inside the corridor: rail head top at y = 0.35 (nothing higher)."""
    if not TRACK_STRIP:
        return
    sh = b.shared
    bed_side = sh.get('bed_side', F(ballast_bed(0.8)), 4.0, 0.14, 'left')
    bed_end = sh.get('bed_end', F(ballast_bed(0.8)), 2.8, 0.14, 'front')
    b.box(1.1, 0, 0, 3.9, 0.14, D_B, all=bed_side, up=sh.get('bed_top', F(ballast_bed(0.95)), 2.8, 9.0, 'up'),
          front=bed_end, back=bed_end)
    sl_up = sh.get('sleeper_up', F(timber((0.172, 0.828))), 2.44, 0.26, 'up')
    sl_side = sh.get('sleeper_side', F(timber()), 0.26, 0.1, 'left')
    sl_end = sh.get('sleeper_end', F(timber()), 2.44, 0.1, 'front')
    n = int(D_B / 0.6)
    for i in range(n):
        zc = 0.3 + 0.6 * i
        b.box(1.28, 0.14, zc - 0.13, 3.72, 0.22, zc + 0.13, all=sl_side, up=sl_up, front=sl_end, back=sl_end,
              left=sl_side, right=sl_side)
    r_up = sh.get('rail_up', F(rail_top()), 0.2, 9.0, 'up')
    r_side = sh.get('rail_side', F(brushed(STEEL_D * 0.78, seams=False)), 9.0, 0.06, 'left')
    r_end = sh.get('rail_end', F(solid(STEEL_D)), 0.2, 0.06, 'front')
    r_web = sh.get('rail_web', F(rail_web()), 9.0, 0.08, 'left')
    r_foot = sh.get('rail_foot', F(rail_web(C('#3E3A35'))), 9.0, 0.04, 'left')
    for xc in (1.7, 3.3):
        b.box(xc - 0.12, 0.22, 0, xc + 0.12, 0.26, D_B, all=r_foot, up=r_foot, front=r_end, back=r_end)
        b.box(xc - 0.04, 0.26, 0, xc + 0.04, 0.30, D_B, all=r_web, up=r_web, front=r_end, back=r_end)
        b.box(xc - 0.1, 0.30, 0, xc + 0.1, RAIL_TOP, D_B, all=r_side, up=r_up, front=r_end, back=r_end)


class Side:
    """Mirror-aware placement on the left (x 0..1.1) or right (x 3.9..5) deck; s = distance from the OUTER edge."""

    def __init__(self, b, name, width=W_B):
        self.b, self.name, self.L, self.W = b, name, name == 'L', width
        self.outer = 'left' if self.L else 'right'
        self.inner = 'right' if self.L else 'left'

    def x(self, s):
        return s if self.L else self.W - s

    def box(self, s0, y0, z0, s1, y1, z1, inner=None, outer=None, **kw):
        xa, xb = self.x(s0), self.x(s1)
        faces = dict(kw)
        for key, face in (('inner', self.inner), ('outer', self.outer)):
            v = inner if key == 'inner' else outer
            if v is not None:
                faces[face] = v(face) if callable(v) else v
        for k, v in list(faces.items()):
            if callable(v):
                faces[k] = v(k)
        return self.b.box(min(xa, xb), y0, z0, max(xa, xb), y1, z1, **faces)

    def face_of(self, which):
        return self.outer if which == 'outer' else self.inner


def deck(b, side, zones=(), centre_line=None, outer_deco=None, tread=C('#6C7279')):
    """Raised side platform: concrete plinth, steel tread slab with tactile studs + safety line, hazard curb."""
    S = Side(b, side)
    sh = b.shared
    x0, x1 = (0.0, 1.1) if S.L else (3.9, 5.0)
    conc = lambda *d: F(concrete(), *d)
    # concrete plinth (inset 0.04 each side so the steel slab overhangs)
    plinth = (x0 + 0.04, 0, 0, x1 - 0.04, 0.48, D_B)
    kw = {S.outer: conc(*(outer_deco or []), band(0.0, 0.06, CONC_D)),
          S.inner: conc(text(0.5, 0.6, 'FICSIT', C('#B9BEC4'), 0.12), band(0.0, 0.06, CONC_D)),
          'front': sh.get('plinth_end', conc(), 1.0, 0.48, 'front'), 'back': sh.get('plinth_end', conc(), 1.0, 0.48, 'back')}
    b.box(*plinth, all=conc(), **kw)
    slab = (x0, 0.48, 0, x1, DECK, D_B)
    top = F(floor(tread), deck_marks(slab, side, zones, centre_line=centre_line))
    steel_side = F(brushed(STEEL_D * 1.05, seams=False), bolts_edge(0.35, 0.25))
    b.box(*slab, all=steel_side, up=top, front=sh.get('slab_end', F(solid(STEEL_D)), 1.1, 0.12, 'front'),
          back=sh.get('slab_end', F(solid(STEEL_D)), 1.1, 0.12, 'back'))
    # hazard curb along the track edge
    cx0, cx1 = (1.0, 1.1) if S.L else (3.9, 4.0)
    haz = sh.get('curb_side', F(hazard(YELLOW, BLACK, 0.07)), 9.0, 0.06, 'left')
    b.box(cx0, DECK, 0, cx1, DECK + 0.06, D_B, all=haz, up=sh.get('curb_top', F(hazard(YELLOW, BLACK, 0.07)), 0.1, 9.0, 'up'),
          front=sh.get('curb_end', F(hazard(YELLOW, BLACK, 0.07)), 0.1, 0.06, 'front'),
          back=sh.get('curb_end', F(hazard(YELLOW, BLACK, 0.07)), 0.1, 0.06, 'back'))
    return S


def bollard(S, s, z, h=0.42, tag='bollard'):
    """Yellow-black mooring bollard on the deck."""
    S.box(s - 0.07, DECK, z - 0.07, s + 0.07, DECK + h, z + 0.07, share=tag,
          all=F(strut(YELLOW, band=None), hband(0.55, 0.75, 0.05)), up=F(solid(GUN)))
    S.box(s - 0.09, DECK + h, z - 0.09, s + 0.09, DECK + h + 0.05, z + 0.09, share=tag + '_cap',
          all=F(solid(GUN)))


def lamp_post(S, s, z, h=1.9, glowing=True, tag='lamppost', reach=0.32, facing=+1):
    """Post with a lamp head that reaches over the deck toward the track (lit)."""
    S.box(s - 0.05, DECK, z - 0.05, s + 0.05, DECK + h, z + 0.05, share=tag + '_pole',
          all=F(strut(GUN, band=YELLOW)), up=F(solid(GUN)))
    S.box(s - 0.09, DECK, z - 0.09, s + 0.09, DECK + 0.12, z + 0.09, share=tag + '_foot', all=F(solid(GUN)))
    a, b_ = (s, s + reach) if facing > 0 else (s - reach, s)
    S.box(a - 0.02, DECK + h - 0.02, z - 0.07, b_ + 0.04, DECK + h + 0.05, z + 0.07, share=tag + '_head',
          all=F(solid(GUN)), down=F(lamp_face(C('#FFF2C4'), True)), flags=['alwaysGlow'])


def newb(st, sh, name, h, kind='buildings', w=5, d=9, ax=2, az=4, geo_name=None):
    b = TB(st, name, w, d, h, ax, az, kind=kind, geo_name=geo_name)
    b.shared = sh
    return b


# =================================================================================================================
# A4) empty_platform - plain dock segment
# =================================================================================================================
def empty_platform(st, sh):
    b = newb(st, sh, 'empty_platform', 2)
    track_strip(b)
    for side in ('L', 'R'):
        S = deck(b, side, centre_line=(1.5, 4.5, 7.5), outer_deco=[text(0.5, 0.5, 'DOCK', C('#B9BEC4'), 0.14)])
        for z in (1.0, 3.2, 5.8, 8.0):
            bollard(S, 0.16, z)
        for z in (2.0, 7.0):
            lamp_post(S, 0.16, z, h=1.3)
        # dock marker: post with a lit sign that faces the train
        S.box(0.28, DECK, 4.38, 0.36, DECK + 0.95, 4.62, share='dock_post', all=F(strut(STEEL, band=YELLOW)), up=F(solid(GUN)))
        sign = lambda face: F(paint(BLUE_D), band(0.0, 0.1, YELLOW), text(0.5, 0.5, 'DOCK', WHITE, 0.2),
                              text(0.5, 0.82, 'A' if side == 'L' else 'B', ORANGE_L, 0.16), bolts_edge(0.2, 0.3))
        S.box(0.24, DECK + 0.95, 3.85, 0.4, DECK + 1.3, 5.15, all=GN(), inner=sign, outer=lambda f: F(paint(BLUE_D), logo(0.5, 0.5, 1.0)),
              flags=['alwaysGlow'])
        # utility hatch + cable duct lying on the deck
        S.box(0.36, DECK, 6.45, 0.9, DECK + 0.07, 7.65, all=GN(), up=GRATE, share='duct')
        S.box(0.4, DECK, 1.7, 0.86, DECK + 0.07, 2.5, all=GN(), up=F(floor(C('#5F646A')), hatch(0.5, 0.5, 0.8, 0.8)), share='hatch')
    b.particle = sh.get('particle_dock', F(paint(BLUE_D), logo(0.5, 0.5, 1.0)), 1.0, 1.0)
    b.export()


def pane(tint=C('#5B93B5'), panels=3, frame=GUN):
    """Glazed wall: tinted glass with sky reflection, diagonal glare and steel mullions."""

    def fn(cv):
        cv.vgrad(0, 0, cv.W, cv.H, tint * 0.95, tint * 0.5)
        u = np.arange(cv.W)[None, :] + np.arange(cv.H)[:, None] * 0.8
        streak = (np.mod(u, 34) < 5)
        cv.a[streak] = cv.a[streak] * 0.82 + 255 * 0.18
        t = max(2, int(0.05 * min(cv.sx, cv.sy)))
        cv.frame(0, 0, cv.W, cv.H, frame, t)
        for i in range(1, panels):
            x = int(cv.W * i / panels)
            cv.rect(x - 1, 0, x + 1, cv.H, frame)
            cv.mul(x - 1, 0, x, cv.H, 1.3)
        cv.rect(0, cv.H // 2 - 1, cv.W, cv.H // 2 + 1, frame, 0.9)
        cv.bevel(0, 0, cv.W, cv.H)
        cv.clean[:] = 1
        return 'none'

    return fn


# =================================================================================================================
# A1) train_station
# =================================================================================================================
def train_station(st, sh):
    b = newb(st, sh, 'train_station', 4)
    track_strip(b)
    # ---------------------------------------------------------------- station side (right deck)
    SR = deck(b, 'R', zones=[(0.55, 8.45, 0.72, 1.0, YELLOW * 0.9)],
              outer_deco=[text(0.5, 0.5, 'STATION', C('#B9BEC4'), 0.16)])
    hall = lambda *d: WH(band(0.0, 0.07, GUN), band(0.84, 0.92, ORANGE), band(0.92, 1.0, GUN), *d)
    HZ0, HZ1, HY1 = 0.7, 8.3, 2.5
    door_faces = lambda face: hall(
        win(0.10, 0.5, 1.0, 0.85, True, bars=2, seed=1), win(0.28, 0.5, 1.0, 0.85, True, bars=2, seed=2),
        sliding_door(0.5, 1.15, 1.35),
        win(0.72, 0.5, 1.0, 0.85, True, bars=2, seed=3), win(0.90, 0.5, 1.0, 0.85, True, bars=2, seed=4),
        )
    SR.box(0.0, DECK, HZ0, 0.7, HY1, HZ1, all=hall(),
           inner=door_faces,
           outer=lambda f: hall(logo(0.22, 0.42, 1.5), text(0.6, 0.42, 'FICSIT RAIL', DARK2, 0.2),
                                vent(0.2, 0.7, 0.8, 0.25), vent(0.5, 0.7, 0.8, 0.25), vent(0.8, 0.7, 0.8, 0.25),
                                warn(0.92, 0.4, 0.3)),
           front=hall(vent(0.3, 0.5, 0.4, 0.8), label(0.75, 0.5, 0.3), text(0.5, 0.12, 'EXIT', ORANGE, 0.12)),
           back=hall(hatch(0.5, 0.5, 0.45, 1.3, label='STAFF'), warn(0.15, 0.45, 0.2)),
           up=GN(vent(0.5, 0.5, 0.6, 5.0)))
    # canopy: one slab over the walkway + hall, steel columns along the platform edge
    canopy_side = lambda f: OR(band(0.0, 0.25, GUN), hband(0.25, 1.0, 0.09))
    SR.box(0.0, 2.5, 0.3, 1.1, 2.65, 8.7, all=OR(),
           inner=canopy_side, outer=OR(band(0.0, 0.3, GUN)),
           up=GN(hatch(0.5, 0.12, 0.6, 1.2, handle=False), hatch(0.5, 0.88, 0.6, 1.2, handle=False),
                 bolts_edge(0.35, 0.3)),
           front=OR(hband(0.0, 1.0, 0.08)), back=OR(hband(0.0, 1.0, 0.08)))
    for z in (0.5, 2.5, 6.5, 8.5):
        SR.box(0.93, DECK, z - 0.08, 1.07, 2.5, z + 0.08, share='pillar', all=STRUT)
    # control tower on the roof: STATION lettering, panorama window, radar
    tower = lambda *d: OR(band(0.0, 0.08, GUN), *d)
    SR.box(0.0, 2.65, 3.0, 1.02, 3.65, 6.0, all=tower(),
           inner=lambda f: tower(text(0.5, 0.27, 'STATION', WHITE, 0.34),
                                 win(0.5, 0.74, 2.75, 0.38, True, tint=C('#3F7EA8'), bars=6, seed=7)),
           outer=lambda f: tower(text(0.5, 0.35, 'CONTROL', WHITE, 0.22), vent(0.5, 0.72, 1.6, 0.3)),
           front=tower(win(0.5, 0.62, 0.6, 0.5, True, bars=1, seed=9), logo(0.5, 0.15, 0.75)),
           back=tower(vent(0.5, 0.5, 0.7, 0.5)),
           up=GN(vent(0.5, 0.3, 0.6, 0.8), hatch(0.5, 0.75, 0.5, 0.5, handle=False)))
    b.box(4.0, 3.65, 5.0, 4.25, 3.9, 5.8, all=OR(), up=GN(vent(0.5, 0.5, 0.7, 0.8)), flags=[])  # HVAC block
    b.box(4.42, 3.65, 3.42, 4.48, 3.78, 3.48, all=F(cylinder(STEEL_D, 'y', rings=0)))            # radar mast
    b.box(4.18, 3.78, 3.39, 4.72, 3.85, 3.51, all=F(arm(STEEL_L)), flags=['spin'])                # radar bar
    b.box(4.86, 3.65, 5.64, 4.92, 3.97, 5.7, all=F(cylinder(STEEL, 'y', rings=0)))                # antenna
    b.box(4.84, 3.95, 5.62, 4.94, 3.99, 5.72, all=F(solid(RED)), flags=['alwaysGlow'])
    connector(b, 3.65, x=4.5, z=4.3)
    # roof plant on the canopy slab
    for z in (1.5, 7.5):
        SR.box(0.3, 2.65, z - 0.3, 0.8, 2.85, z + 0.3, all=F(cylinder(STEEL, 'y', rings=0)), up=F(fan_top()), share='roof_fan')
    # ticket terminals against the hall wall
    for z in (1.4, 7.2):
        SR.box(0.7, DECK, z - 0.3, 0.86, 1.55, z + 0.3, all=DK(band(0.0, 0.1, YELLOW)), share='terminal')
        SR.box(0.86, 0.95, z - 0.26, 0.885, 1.45, z + 0.26, all=GN(), inner=F(screen('text', seed=int(z * 3))),
               flags=['alwaysGlow'])
    # departure boards hanging from the canopy edge (face the train)
    for z in (1.5, 7.5):
        SR.box(1.04, 2.05, z - 0.55, 1.1, 2.48, z + 0.55, all=GN(), inner=F(screen('bars', seed=int(z * 5))),
               flags=['alwaysGlow'])
    # platform furniture: bollards + lamp posts along the outer/inner edges
    for z in (3.0, 6.0):
        bollard(SR, 0.95, z)
    # ---------------------------------------------------------------- waiting platform (left deck)
    SL = deck(b, 'L', zones=[(1.4, 7.6, 0.0, 0.55, YELLOW * 0.9)],
              outer_deco=[text(0.5, 0.5, 'PLATFORM 1', C('#B9BEC4'), 0.14)])
    SL.box(0.02, DECK, 1.6, 0.1, 1.95, 7.4, all=GN(), inner=F(pane(C('#7FB4D0'), 4)), outer=F(pane(C('#5E97B6'), 4)),
           front=F(solid(GUN)), back=F(solid(GUN)))
    SL.box(0.0, 2.05, 1.3, 0.95, 2.19, 7.7, all=OR(), inner=lambda f: OR(hband(0, 1, 0.09)), up=GN(vent(0.5, 0.25, 0.5, 0.9),
           vent(0.5, 0.75, 0.5, 0.9), bolts_edge(0.35, 0.3)), front=OR(hband(0, 1, 0.08)), back=OR(hband(0, 1, 0.08)))
    for z in (1.4, 4.5, 7.6):
        SL.box(0.8, DECK, z - 0.07, 0.92, 2.05, z + 0.07, share='pillar_s', all=STRUT)
    seat = lambda f: F(paint(C('#2C4A66')), hband(0.0, 0.25, 0.05))
    for z0, z1 in ((2.2, 3.7), (5.3, 6.8)):
        SL.box(0.2, DECK, z0, 0.55, 0.9, z1, all=GN(), up=F(floor(C('#4B4F55')), band(0.4, 0.6, ORANGE_D)), share='bench')
        SL.box(0.14, 0.9, z0, 0.2, 1.4, z1, all=GN(), inner=lambda f: OR(text(0.5, 0.5, 'FICSIT', WHITE, 0.2)),
               outer=lambda f: OR(), share='bench_back')
    # timetable pillar with lit displays (both sides)
    SL.box(0.4, DECK, 8.2, 0.68, 1.95, 8.7, all=DK(band(0.0, 0.08, YELLOW)), front=DK(logo(0.5, 0.3, 0.5)),
           back=DK(logo(0.5, 0.3, 0.5)), share='pillar_board')
    SL.box(0.68, 1.0, 8.24, 0.71, 1.85, 8.66, all=GN(), inner=F(screen('graph', seed=41)), flags=['alwaysGlow'])
    SL.box(0.37, 1.0, 8.24, 0.4, 1.85, 8.66, all=GN(), outer=F(screen('text', seed=42)), flags=['alwaysGlow'])
    for z in (0.6, 8.4):
        lamp_post(SL, 0.7, z, h=1.7, facing=+1, reach=0.3, tag='lp_st')
    b.particle = sh.get('particle_station', F(paint(ORANGE), logo(0.5, 0.5, 1.0)), 1.0, 1.0)
    b.export()


# ------------------------------------------------------------------------------------------------------------------
# stacked-box cylinders (tanks, pipes, stubs)
# ------------------------------------------------------------------------------------------------------------------
def tube(b, axis, c0, c1, R, a0, a1, color, bands=(), seams=(), steps=None, decor=None, cap0='plain', cap1='plain',
         soot=0.0, share=None, flags=(), kind='metal'):
    """Cylinder along `axis` built from stacked boxes (an octagon-ish prism, like fluid_buffer).

    axis 'z': c0 = centre x, c1 = centre y, a0..a1 = z range;  'x': c0 = centre z, c1 = centre y, a0..a1 = x range;
    'y': c0 = centre x, c1 = centre z, a0..a1 = y range.  bands = (along0, along1, colour); seams = along positions.
    decor(level, face) -> list of decals for that face (level 0 = middle box, +n upper, -n lower).
    Shading comes from the true surface normal at each pixel, so all boxes read as one round body.
    """
    if steps is None:
        steps = 3 if R >= 0.75 else (2 if R >= 0.2 else 1)
    if steps == 3:
        bnd, hws = [0, 0.45, 0.8, 1.0], [0.95, 0.78, 0.46]
    elif steps == 2:
        bnd, hws = [0, 0.6, 1.0], [0.93, 0.56]
    else:
        bnd, hws = [0, 1.0], [1.0]
    levels = [(0, -bnd[1], bnd[1], hws[0])]
    for i in range(1, steps):
        levels.append((i, bnd[i], bnd[i + 1], hws[i]))
        levels.append((-i, -bnd[i + 1], -bnd[i], hws[i]))
    along_faces = {'z': ('left', 'right', 'up', 'down'), 'x': ('front', 'back', 'up', 'down'),
                   'y': ('front', 'back', 'left', 'right')}[axis]
    lo_face = {'z': 'down', 'x': 'down', 'y': 'back'}[axis]   # face toward -q
    hi_face = {'z': 'up', 'x': 'up', 'y': 'front'}[axis]      # face toward +q
    for (lvl, q0, q1, hw) in levels:
        p0, p1 = c0 - hw * R, c0 + hw * R
        qa, qb = c1 + q0 * R, c1 + q1 * R
        if axis == 'z':
            box = (p0, qa, a0, p1, qb, a1)
        elif axis == 'x':
            box = (a0, qa, p0, a1, qb, p1)
        else:
            box = (p0, a0, qa, p1, a1, qb)
        faces = {}
        for f in FACES:
            if f in along_faces:
                base = tube_base(box, axis, c0, c1, R, color, bands, seams, soot, kind=kind)
            else:
                base = tube_base(box, axis, c0, c1, R, color, cap_style=(cap0 if _is_low_cap(axis, f) else cap1), kind=kind)
            faces[f] = F(base, *(decor(lvl, f) if decor else []))
        # faces buried inside the neighbouring level are never seen
        if lvl > 0:
            faces[lo_face] = DOWN_ID[0]
        elif lvl < 0:
            faces[hi_face] = DOWN_ID[0]
        b.box(*box, share=(None if share is None else '%s/%d' % (share, lvl)), flags=flags, **faces)


def _is_low_cap(axis, face):
    """True for the cap at the low end of the axis range."""
    return {'z': 'back', 'x': 'left', 'y': 'down'}[axis] == face


CORRIDOR = (1.1, 3.9)


def validate(b):
    """Buildings: nothing but the ballast/sleeper/rail strip may enter the track corridor above y = 0.4."""
    bad = []
    for i, p in enumerate(b.parts):
        (x0, y0, z0), (x1, y1, z1) = p['from'], p['to']
        if x1 > CORRIDOR[0] + 1e-6 and x0 < CORRIDOR[1] - 1e-6 and y1 > 0.4 + 1e-6:
            bad.append((i, p['from'], p['to']))
        if min(x0, x1) < -0.05 or max(x0, x1) > W_B + 0.05 or z0 < -0.05 or z1 > D_B + 0.05 or y1 > b.h + 1e-6:
            bad.append((i, 'outside footprint', p['from'], p['to']))
    if bad:
        raise SystemExit('%s: geometry violates the corridor / footprint rules: %s' % (b.name, bad[:6]))


def gantry(S, zs=(0.35, 8.65), y_top=3.0, tag='gantry'):
    """Portal gantry along the deck: corner columns, two rails, cross beams and a hoist trolley (never past the track edge)."""
    z0, z1 = zs
    beam = lambda: F(paint(GUN), band(0.0, 0.16, YELLOW), hband(0.16, 0.34, 0.06), bolts_edge(0.3, 0.3))
    for s0, s1 in ((0.02, 0.16), (0.92, 1.06)):
        for z in zs:
            S.box(s0, DECK, z - 0.07, s1, y_top - 0.15, z + 0.07, share=tag + '_col', all=STRUT)
        S.box(s0, y_top - 0.15, z0 - 0.09, s1, y_top, z1 + 0.09, share=tag + '_rail' + str(s0), all=beam(), up=GRATE)
    for z in zs:
        S.box(0.16, y_top - 0.15, z - 0.08, 0.92, y_top, z + 0.08, share=tag + '_x', all=beam(), up=GRATE)


def container(S, s0, s1, z0, z1, y0, y1, color, tag_text, num, share=None):
    box = lambda *d: F(corrugated(color), *d)
    S.box(s0, y0, z0, s1, y1, z1, all=box(),
          inner=lambda f: box(logo(0.5, 0.36, 1.4), text(0.5, 0.72, tag_text, WHITE, 0.14)),
          outer=lambda f: box(text(0.5, 0.4, num, WHITE, 0.2), warn(0.5, 0.74, 0.26)),
          front=box(custom(_container_doors)), back=box(custom(_container_doors)),
          up=F(paint(color), hband(0.0, 0.06, 0.06), hband(0.94, 1.0, 0.06)), share=share)


# =================================================================================================================
# A2) freight_platform - item loading dock with gantry, containers and belt ports
# =================================================================================================================
def freight_platform(st, sh):
    b = newb(st, sh, 'freight_platform', 4)
    track_strip(b)
    for side in ('L', 'R'):
        S = deck(b, side, zones=[(1.85, 3.15, 0.0, 0.5, YELLOW * 0.9), (5.85, 7.15, 0.0, 0.5, YELLOW * 0.9)],
                 outer_deco=[text(0.5, 0.5, 'FREIGHT', C('#B9BEC4'), 0.14)])
        # belt ports on the outer face: z=2.5 input (blue), z=6.5 output (orange)
        for zc, out in ((2.5, False), (6.5, True)):
            S.box(-0.02, DECK, zc - 0.4, 0.24, 1.6, zc + 0.4, all=GN(), outer=F(port(out)), up=GRATE)
            # loader: housing + hopper + chute + spinning arm
            body = lambda *d: OR(band(0.0, 0.1, GUN), hband(0.0, 0.07, 0.08), *d)
            S.box(0.24, DECK, zc - 0.62, 0.96, 1.7, zc + 0.62, all=body(), up=GN(hatch(0.5, 0.5, 0.5, 0.5, handle=False), bolts_edge()),
                  inner=lambda f, zc=zc, out=out: body(text(0.5, 0.3, 'LOADER' if not out else 'UNLOAD', WHITE, 0.15),
                                                      leds(0.5, 0.62, 3), label(0.5, 0.82, 0.3)),
                  outer=body(vent(0.5, 0.55, 1.0, 0.5)),
                  front=body(vent(0.5, 0.55, 0.8, 0.5), warn(0.85, 0.3, 0.22)),
                  back=body(vent(0.5, 0.55, 0.8, 0.5), warn(0.15, 0.3, 0.22)))
            S.box(0.32, 1.7, zc - 0.45, 0.88, 2.25, zc + 0.45, all=GN(hband(0.0, 0.3, 0.08)), up=F(vents()))
            S.box(0.96, 0.78, zc - 0.32, 1.08, 1.3, zc + 0.32, all=GN(), inner=HAZ)         # chute mouth toward the train
            S.box(0.44, 2.25, zc - 0.13, 0.7, 2.75, zc + 0.13, all=F(arm(YELLOW)), flags=['spin'])
            S.box(0.34, 2.75, zc - 0.1, 0.8, 2.85, zc + 0.1, all=F(arm(YELLOW)), flags=['spin'])
            # working lamp (lit while running)
            S.box(0.5, 2.55, zc - 0.3, 0.62, 2.65, zc - 0.22, share='fr_lamp', all=GN(), down=lens(C('#FFF2C4'), False),
                  flags=['glow'], active={'down': lens(C('#FFF2C4'), True)})
        # gantry with a container stack between the loaders + trolley hoist
        gantry(S)
        col1, col2 = (ORANGE, C('#8F969E')) if side == 'L' else (C('#8F969E'), ORANGE)
        container(S, 0.2, 0.86, 3.4, 5.6, DECK, 1.6, col1, 'FICSIT CARGO', 'NO. 1' if side == 'L' else 'NO. 3')
        container(S, 0.2, 0.86, 3.4, 5.6, 1.6, 2.6, col2, 'FREIGHT', 'NO. 2' if side == 'L' else 'NO. 4')
        S.box(0.16, 2.85, 4.36, 0.92, 3.0, 4.64, share='trolley', all=YL(hband(0.0, 1.0, 0.08)), up=GRATE)
        S.box(0.3, 2.62, 4.2, 0.78, 2.85, 4.8, all=YL(), up=GN(), share='hoist')
        for zz in (4.3, 4.7):
            S.box(0.36, 2.6, zz - 0.02, 0.4, 2.62, zz + 0.02, all=F(solid(STEEL_D)), share='hoist_c')
        for zz in (0.6, 8.4):
            bollard(S, 0.1, zz)
    b.particle = sh.get('particle_freight', F(paint(ORANGE), logo(0.5, 0.5, 1.0)), 1.0, 1.0)
    b.export()


# =================================================================================================================
# A3) fluid_freight_platform - pumping dock with pipe manifold, buffer tank and stub connections
# =================================================================================================================
def fluid_freight_platform(st, sh):
    b = newb(st, sh, 'fluid_freight_platform', 4)
    track_strip(b)
    for side in ('L', 'R'):
        S = deck(b, side, zones=[(3.25, 5.75, 0.0, 0.62, C('#3FA7E0'))],
                 outer_deco=[text(0.5, 0.5, 'FLUID', C('#B9BEC4'), 0.14)])
        lo = lambda s0, s1: (min(S.x(s0), S.x(s1)), max(S.x(s0), S.x(s1)))
        # ---- pump station in the middle of the deck
        pump = lambda *d: OR(band(0.0, 0.1, GUN), hband(0.0, 0.07, 0.08), *d)
        S.box(0.55, DECK, 3.45, 1.02, 2.3, 5.55, all=pump(), up=GN(vent(0.5, 0.3, 0.3, 0.5), hatch(0.5, 0.72, 0.3, 0.4, handle=False)),
              inner=lambda f: pump(text(0.5, 0.16, 'PUMP', WHITE, 0.14), gauge(0.26, 0.52, 0.12, 0.7), gauge(0.74, 0.52, 0.12, 0.45),
                                   leds(0.5, 0.8, 3), hband(0.9, 0.96)),
              outer=pump(),
              front=pump(vent(0.5, 0.5, 0.5, 0.5)), back=pump(vent(0.5, 0.5, 0.5, 0.5)))
        # ---- blue pipe stub out of the outer face at z = 4.5, y 0.9..1.9
        xa, xb = lo(-0.02, 0.56)
        bands = [(lo(0.05, 0.17)[0], lo(0.05, 0.17)[1], STEEL_L), (lo(0.36, 0.5)[0], lo(0.36, 0.5)[1], STEEL_L)]
        seams = [lo(0.11, 0.11)[0], lo(0.43, 0.43)[0]]
        tube(b, 'x', 4.5, 1.4, 0.5, xa, xb, BLUE, bands=bands, seams=seams,
             cap0='pipe' if S.L else 'plain', cap1='plain' if S.L else 'pipe', share='stub' + side)
        # ---- small round buffer tank (vertical) + surge pipe on top
        tz = 1.7 if side == 'L' else 7.3
        tank_decor = lambda lvl, face: ([text(0.5, 0.42, 'FLUID', BLUE_D, 0.13), text(0.5, 0.56, 'BUFFER', BLUE_D, 0.11)]
                                        if lvl == 0 and face in ('left', 'right') else [])
        tube(b, 'y', S.x(0.5), tz, 0.44, DECK, 2.35, WHITE,
             bands=[(DECK + 0.05, DECK + 0.2, BLUE), (2.13, 2.25, BLUE)], seams=[1.3, 1.75], decor=tank_decor,
             cap1='manway', share='tank' + side)
        S.box(0.35, 2.35, tz - 0.16, 0.65, 2.47, tz + 0.16, all=GN(hband(0, 1, 0.08)), up=F(cylinder(YELLOW, 'y', rings=0)), share='tank_hat')
        tube(b, 'y', S.x(0.5), tz, 0.09, 2.47, 2.6, STEEL, steps=1, share='riser1')
        # manifold pipe along z above everything, risers down into tank and pump
        z_lo, z_hi = (tz, 4.5) if tz < 4.5 else (4.5, tz)
        tube(b, 'z', S.x(0.5), 2.62, 0.13, z_lo - 0.06, z_hi + 0.06, STEEL, bands=[(z_lo + 0.5, z_lo + 0.6, BLUE), (z_hi - 0.6, z_hi - 0.5, BLUE)],
             steps=2, share='manifold' + side)
        tube(b, 'y', S.x(0.78), 4.5, 0.09, 2.3, 2.6, STEEL, steps=1, share='riser2')
        # ---- blue status lamps on the pump (lit while working) + beacon on top
        for zz in (3.75, 5.25):
            S.box(1.02, 1.55, zz - 0.11, 1.08, 1.85, zz + 0.11, share='fl_lamp', all=GN(), inner=F(lamp_face(C('#5BC8FF'), False)),
                  flags=['glow'], active={S.inner: F(lamp_face(C('#5BC8FF'), True))})
        S.box(0.7, 2.3, 4.4, 0.86, 2.42, 4.6, share='fl_beacon', all=F(lamp_face(C('#5BC8FF'), False)), flags=['glow'],
              active={f: F(lamp_face(C('#5BC8FF'), True)) for f in FACES})
        # ---- hazard-ringed loading nozzle toward the train + hand valve wheels
        xa, xb = lo(1.02, 1.09)
        tube(b, 'x', 4.5, 1.25, 0.13, xa, xb, STEEL_D, steps=1, share='nozzle' + side)
        for zz in (3.62, 5.38):
            S.box(0.72, 0.85, zz - 0.02 if zz < 4.5 else zz - 0.01, 0.98, 1.11, zz + 0.01 if zz < 4.5 else zz + 0.02, share='valve',
                  all=F(paint(RED), ring(0.5, 0.5, 0.36, BLACK, 0.1), ring(0.5, 0.5, 0.1, BLACK, 0.08)))
        # ---- electrical cabinet at the far end + bollards
        ez = 7.3 if side == 'L' else 1.7
        cab = lambda *d: F(brushed(C('#4A5058')), band(0.0, 0.1, YELLOW), *d)
        S.box(0.2, DECK, ez - 0.35, 0.75, 1.75, ez + 0.35, all=cab(),
              inner=lambda f: cab(console(0.5, 0.42, 0.62, 0.7, on=True, kind='bars', seed=31), leds(0.5, 0.86, 3, True)),
              outer=lambda f: cab(logo(0.5, 0.4, 0.6)),
              front=cab(warn(0.5, 0.5, 0.3)), back=cab(warn(0.5, 0.5, 0.3)))
        for zz in (0.6, 8.4):
            bollard(S, 0.1, zz)
    b.particle = sh.get('particle_fluid', F(paint(BLUE_D), logo(0.5, 0.5, 1.0)), 1.0, 1.0)
    b.export()


# =================================================================================================================
# B) rolling stock helpers
# =================================================================================================================
VW = 3.0            # vehicle frame width (centre x = 1.5)
RAIL_X = (0.7, 2.3)


def validate_vehicle(b, L, top=3.62):
    bad = []
    for i, p in enumerate(b.parts):
        (x0, y0, z0), (x1, y1, z1) = p['from'], p['to']
        if y0 < -1e-6 or y1 > top or x0 < 0.1 - 1e-6 or x1 > 2.9 + 1e-6 or z0 < -1e-6 or z1 > L + 1e-6:
            bad.append((i, p['from'], p['to']))
    if bad:
        raise SystemExit('%s: vehicle geometry out of bounds: %s' % (b.name, bad[:6]))


def wheel(b, xc, zc, R=0.45, w=0.16):
    """Stepped-octagon wheel from three non-overlapping boxes; every wheel of the same size shares its textures."""
    cy = R
    hw, hc = 0.93 * R, 0.56 * R
    for i, (dz, y0, y1) in enumerate(((hw, cy - 0.6 * R, cy + 0.6 * R), (hc, cy + 0.6 * R, cy + R), (hc, cy - R, cy - 0.6 * R))):
        canon = (-w / 2, y0, -dz, w / 2, y1, dz)
        b.box(xc - w / 2, y0, zc - dz, xc + w / 2, y1, zc + dz, all=F(wheel_face(canon, 0, cy, 0, R)),
              share='wheel%d_%d' % (int(R * 100), i), flags=['wheel'])


def bogie(b, zc, wb=1.6, R=0.45, motors=True):
    """Two-axle bogie: 4 wheels, axles, journal boxes, side frames, bolster and (optionally) traction motors."""
    for dz in (-wb / 2, wb / 2):
        z = zc + dz
        for xc in RAIL_X:
            wheel(b, xc, z, R)
        b.box(0.78, R - 0.06, z - 0.06, 2.22, R + 0.06, z + 0.06, share='axle', all=F(cylinder(STEEL, 'z', rings=0)))
        for xa, xb in ((0.5, 0.62), (2.38, 2.5)):
            b.box(xa, R - 0.11, z - 0.13, xb, R + 0.11, z + 0.13, share='axlebox', all=GN(band(0.0, 0.2, YELLOW)))
        if motors:
            b.box(1.03, 0.28, z - 0.2, 1.97, 0.66, z + 0.2, share='motor', all=F(paint(ORANGE_D), band(0.0, 0.12, GUN)),
                  up=GN(vent(0.5, 0.5, 0.6, 0.5)))
    for xa, xb in ((0.84, 1.0), (2.0, 2.16)):
        b.box(xa, 0.3, zc - wb / 2 - 0.3, xb, 0.72, zc + wb / 2 + 0.3, share='bogie_side', all=GN(hband(0.0, 0.18, 0.07)),
              up=GRATE)
    b.box(0.98, 0.42, zc - 0.13, 2.02, 0.62, zc + 0.13, share='transom', all=GN())
    b.box(1.16, 0.72, zc - 0.32, 1.84, 0.98, zc + 0.32, share='bolster', all=F(paint(GUN), band(0.0, 0.2, YELLOW)))


def end_gear(b, z_face, d, z_end, body=(0.2, 2.8), beam_top=1.4, colour=ORANGE):
    """Buffer beam with hazard face, two buffers, centre coupler with knuckle and side coupler hooks.
    d = +1 for the front end (beam in front of z_face), -1 for the rear end."""
    z_out = z_face + d * 0.26
    zlo, zhi = (z_face, z_out) if d > 0 else (z_out, z_face)
    face = 'front' if d > 0 else 'back'
    haz = F(paint(colour), hband(0.0, 0.42, 0.11), band(0.42, 0.5, GUN), leds(0.5, 0.75, 2, True))
    b.box(body[0], 0.8, zlo, body[1], beam_top, zhi, share='beam' + face, all=F(paint(colour), band(0.0, 0.14, GUN)), **{face: haz})
    for xc in (0.6, 2.4):
        zb0, zb1 = (z_out, z_out + d * 0.08) if d > 0 else (z_out + d * 0.08, z_out)
        b.box(xc - 0.14, 1.0, zb0, xc + 0.14, 1.28, zb1, share='buffer' + face, all=F(cylinder(STEEL_L, 'z', rings=0)))
    zc0, zc1 = (z_out, z_end - 0.1) if d > 0 else (z_end + 0.1, z_out)
    b.box(1.4, 1.0, zc0, 1.6, 1.16, zc1, share='draw' + face, all=GN(hband(0.0, 1.0, 0.05)))
    kz0, kz1 = (z_end - 0.1, z_end) if d > 0 else (z_end, z_end + 0.1)
    b.box(1.28, 0.95, kz0, 1.72, 1.22, kz1, share='knuckle' + face, all=F(paint(GUN), band(0.3, 0.45, YELLOW)))
    for xc in (0.42, 2.58):
        hz0, hz1 = (z_out, z_end - 0.07) if d > 0 else (z_end + 0.07, z_out)
        b.box(xc - 0.05, 1.02, hz0, xc + 0.05, 1.12, hz1, share='hookarm' + face, all=F(solid(STEEL_D)))
        kz0, kz1 = (z_end - 0.07, z_end) if d > 0 else (z_end, z_end + 0.07)
        b.box(xc - 0.06, 1.12, kz0, xc + 0.06, 1.28, kz1, share='hooktip' + face, all=F(paint(YELLOW), band(0.0, 0.3, BLACK)))


def handrails(b, z0, z1, y_top, step=1.3, both=True, tag='hr', y_base=1.18, xs=((0.1, 0.15), (2.85, 2.9))):
    """Walkway handrails along both flanks: posts every `step` + a top and a mid rail (rails inset 0.006 so no face is coplanar)."""
    e = 0.006
    for (xa, xb) in xs:
        n = max(1, int(round((z1 - z0) / step)))
        for i in range(n + 1):
            z = z0 + (z1 - z0) * i / n
            b.box(xa, y_base, z - 0.03, xb, y_top - 0.06, z + 0.03, share=tag + '_post', all=F(solid(YELLOW)))
        b.box(xa + e, y_top - 0.06, z0 - 0.03, xb - e, y_top, z1 + 0.03, share=tag + '_rail' + str(int((z1 - z0) * 10)), all=F(solid(YELLOW)))
        if y_top - y_base > 0.5:
            b.box(xa + e, y_base + 0.25, z0 - 0.03, xb - e, y_base + 0.3, z1 + 0.03, share=tag + '_mid' + str(int((z1 - z0) * 10)), all=F(solid(YELLOW)))


def lens(col, on=True):
    return F(lamp_face(col, on))


# ---- painters for cab glass ------------------------------------------------------------------------------------------
def windshield(lit=False, tint=C('#3C7DA6')):
    """Wide windscreen: sky reflection over a dark cab; the dashboard, seat backs and roof lamp are painted in behind
    the glass (they glow when the train runs)."""

    def fn(cv):
        cv.vgrad(0, 0, cv.W, cv.H, tint * (1.0 if lit else 0.86), tint * 0.42)
        W, H = cv.W, cv.H
        # room interior behind the glass
        cv.rect(1, int(H * 0.5), W - 1, H - 1, C('#0F1F2B') if not lit else C('#3A3428'), 0.8)
        # dashboard band + screens
        dy = int(H * 0.72)
        cv.rect(1, dy, W - 1, H - 1, C('#15181C'))
        for i, cx in enumerate((0.22, 0.5, 0.78)):
            sx0, sx1 = int(W * (cx - 0.11)), int(W * (cx + 0.11))
            cv.rect(sx0, dy + 2, sx1, dy + max(4, int(H * 0.16)), (C('#7FE8FF') if lit else C('#1B3442')))
            if lit:
                cv.rect(sx0 + 1, dy + 3, sx0 + 1 + (sx1 - sx0) // 2, dy + 4, WHITE, 0.7)
        # seat backs
        for cx in (0.3, 0.7):
            cv.rect(int(W * (cx - 0.09)), int(H * 0.42), int(W * (cx + 0.09)), dy, C('#1A2A38') if not lit else C('#4A3E30'))
        # cab roof lamp
        if lit:
            cv.rect(int(W * 0.44), 1, int(W * 0.56), max(3, int(H * 0.08)), C('#FFF0B0'))
        # glare
        u = np.arange(W)[None, :] + np.arange(H)[:, None] * 0.9
        streak = ((np.mod(u, 46) < 7) | ((np.mod(u + 20, 46) < 2)))
        cv.a[streak] = cv.a[streak] * 0.78 + 255 * 0.22
        t = max(2, int(0.06 * cv.sx))
        cv.frame(0, 0, W, H, GUN, t)
        cv.bevel(0, 0, W, H)
        cv.rect(int(W * 0.5) - 1, 0, int(W * 0.5) + 1, H, GUN) if False else None
        cv.clean[:] = 1
        return 'none'

    return fn


def sidewin(lit=False, tint=C('#3C7DA6')):
    """Sliding side window strip: reflection + hint of the lit cab behind it."""

    def fn(cv):
        cv.vgrad(0, 0, cv.W, cv.H, tint * (1.0 if lit else 0.85), tint * (0.5 if lit else 0.38))
        if lit:
            cv.rect(2, cv.H // 2, cv.W - 2, cv.H - 2, C('#FFD98A'), 0.35)
        u = np.arange(cv.W)[None, :] + np.arange(cv.H)[:, None] * 1.1
        streak = (np.mod(u, 40) < 6)
        cv.a[streak] = cv.a[streak] * 0.8 + 255 * 0.2
        t = max(1, int(0.05 * cv.sy))
        cv.frame(0, 0, cv.W, cv.H, GUN, t)
        cv.rect(cv.W // 2 - 1, 0, cv.W // 2 + 1, cv.H, GUN)
        cv.bevel(0, 0, cv.W, cv.H)
        cv.clean[:] = 1
        return 'none'

    return fn


def interior(c=C('#B9BEC5')):
    def fn(cv):
        cv.fill(c)
        cv.a *= (1 + 0.05 * cv.lownoise(0.3))[..., None]
        for y in range(int(0.3 * cv.sy), cv.H, max(6, int(0.45 * cv.sy))):
            cv.mul(0, y, cv.W, y + 1, 0.8)
        cv.bevel(0, 0, cv.W, cv.H, 1.1, 0.8)
        return 'paint'

    return fn


def seat(c=C('#33485E')):
    def fn(cv):
        cv.fill(c)
        cv.a *= (1 + 0.08 * cv.lownoise(0.15))[..., None]
        cv.mul(0, 0, cv.W, 1, 1.35)
        cv.rect(cv.W // 2, 1, cv.W // 2 + 1, cv.H - 1, c * 0.6)
        cv.bevel(0, 0, cv.W, cv.H)
        return 'rough'

    return fn


# =================================================================================================================
# B1) locomotive
# =================================================================================================================
def locomotive(st, sh):
    L = 9.0
    b = newb(st, sh, 'locomotive', 4, kind='vehicles', w=3, d=int(L), ax=1, az=0)
    for zc in (2.0, 7.0):
        bogie(b, zc)
    # ---- chassis, battery boxes, buffer beams + couplers
    b.box(0.2, 0.98, 0.5, 2.8, 1.18, 8.5, all=F(paint(GUN), band(0.7, 1.0, ORANGE)), up=F(floor(C('#5C6167'))))
    b.box(0.3, 0.8, 3.3, 2.7, 0.98, 5.7, all=F(paint(DARK2), hband(0.6, 1.0, 0.06), vent(0.5, 0.4, 0.5, 0.35)),
          left=F(paint(DARK2), text(0.5, 0.45, 'BATTERY', ORANGE_L, 0.4), hband(0.85, 1.0, 0.06)),
          right=F(paint(DARK2), text(0.5, 0.45, 'BATTERY', ORANGE_L, 0.4), hband(0.85, 1.0, 0.06)))
    end_gear(b, 8.5, +1, 9.0)
    end_gear(b, 0.5, -1, 0.0)
    # ---- machinery hood (behind the cab)
    body = lambda *d: F(paint(ORANGE), band(0.9, 1.0, GUN), *d)

    def hood_side(f):
        return F(paint(ORANGE), band(0.83, 1.0, GUN), hband(0.77, 0.83, 0.06),
                 logo(zu(f, 0.2), 0.24, 1.15), text(zu(f, 0.56), 0.24, 'LOCO-01', WHITE, 0.4),
                 vent(zu(f, 0.36), 0.62, 0.95, 0.5), vent(zu(f, 0.68), 0.62, 0.95, 0.5),
                 hatch(zu(f, 0.9), 0.55, 0.62, 1.0, label='HV'), warn(zu(f, 0.06), 0.55, 0.28))

    b.box(0.28, 1.18, 0.5, 2.72, 2.75, 6.2, all=body(), left=hood_side('left'), right=hood_side('right'),
          front=F(paint(ORANGE_D)),
          back=body(text(0.5, 0.22, 'LOCO-01', WHITE, 0.3), hatch(0.3, 0.62, 0.55, 0.85, label='REAR'), vent(0.72, 0.62, 0.55, 0.6),
                    warn(0.5, 0.86, 0.2)),
          up=GN())
    b.box(0.4, 2.75, 0.62, 2.6, 2.85, 6.1, all=GN(hband(0.0, 1.0, 0.08)), up=F(floor(C('#63686E')), vent(0.5, 0.86, 1.4, 0.16)))
    # roof plant: two cooling fans, HV cabinet, pantograph
    for xc in (0.95, 2.05):
        b.box(xc - 0.38, 2.85, 1.0, xc + 0.38, 3.05, 1.76, all=F(cylinder(STEEL, 'y', rings=0)), up=F(fan_top()), share='roof_fan')
    b.box(0.6, 2.85, 4.85, 2.4, 3.1, 5.9, all=F(paint(GUN), band(0.0, 0.2, ORANGE)), up=GN(vent(0.3, 0.5, 0.4, 0.8), vent(0.7, 0.5, 0.4, 0.8)),
          left=F(paint(GUN), text(0.5, 0.5, 'HV', YELLOW, 0.4), warn(0.15, 0.5, 0.3)),
          right=F(paint(GUN), text(0.5, 0.5, 'HV', YELLOW, 0.4), warn(0.85, 0.5, 0.3)))
    b.box(0.8, 2.85, 2.9, 2.2, 2.95, 4.3, all=GN(), up=GRATE)
    for xc in (0.88, 2.12):
        for zc in (3.05, 4.15):
            b.box(xc - 0.07, 2.95, zc - 0.07, xc + 0.07, 3.17, zc + 0.07, share='insulator', all=INSULATOR_ID)
    b.box(0.85, 3.17, 3.0, 2.15, 3.24, 4.2, all=F(solid(GUN)), share='pan_frame')
    for xc in (1.15, 1.85):
        b.box(xc - 0.05, 3.24, 3.2, xc + 0.05, 3.32, 3.6, all=F(solid(STEEL)), share='pan_a')
        b.box(xc - 0.05, 3.32, 3.4, xc + 0.05, 3.4, 3.8, all=F(solid(STEEL)), share='pan_b')
        b.box(xc - 0.05, 3.4, 3.6, xc + 0.05, 3.46, 3.9, all=F(solid(STEEL)), share='pan_c')
    b.box(0.75, 3.44, 3.62, 2.25, 3.52, 3.92, all=F(solid(GUN)), up=F(rail_top()), share='pan_head')
    # ---- driver cab: hollow shell so the console and seats show through the side windows
    CZ0, CZ1 = 6.2, 8.4
    wall = lambda *d: F(paint(ORANGE), *d)
    inn = F(interior())
    for side in ('L', 'R'):
        S = Side(b, side, VW)
        low = lambda f: wall(band(0.86, 1.0, GUN), text(zu(f, 0.55), 0.45, 'FICSIT', WHITE, 0.3))
        S.box(0.2, 1.18, CZ0, 0.3, 1.75, CZ1, all=wall(), outer=low, inner=inn)
        S.box(0.2, 2.75, CZ0, 0.3, 3.05, CZ1, all=wall(hband(0.0, 0.15, 0.06)), outer=wall(band(0.0, 0.2, GUN)), inner=inn)
        S.box(0.2, 1.75, CZ0, 0.3, 2.75, 6.85, all=wall(), outer=lambda f: wall(hatch(zu(f, 0.5), 0.5, 0.42, 0.75, label='CAB'), warn(zu(f, 0.5), 0.86, 0.14)),
              inner=inn)
        S.box(0.2, 1.75, 8.2, 0.3, 2.75, CZ1, all=wall(), outer=wall(), inner=inn)
        S.box(0.235, 2.35, 6.85, 0.275, 2.75, 8.2, all=GN(), outer=F(sidewin(False)), inner=F(sidewin(False)),
              flags=['glow'], active={S.outer: F(sidewin(True)), S.inner: F(sidewin(True))})
        # step + grab handle at the door
        S.box(0.1, 0.72, CZ0 + 0.05, 0.2, 0.8, CZ0 + 0.6, share='step', all=GN(), up=GRATE)
        S.box(0.1, 0.96, CZ0 + 0.05, 0.2, 1.04, CZ0 + 0.6, share='step', all=GN(), up=GRATE)
        S.box(0.13, 1.2, 6.83, 0.18, 2.5, 6.9, share='grab', all=F(solid(YELLOW)))
    b.box(0.3, 1.18, CZ0, 2.7, 1.26, 8.4, all=GN(), up=F(floor(C('#3F444A')), hband(0.0, 0.03), hband(0.97, 1.0)))
    b.box(0.3, 1.26, CZ0, 2.7, 3.05, CZ0 + 0.1, all=inn, back=F(paint(ORANGE_D), hatch(0.5, 0.5, 0.7, 1.5, label='ENGINE')))
    b.box(0.2, 3.05, CZ0, 2.8, 3.15, 8.62, all=F(paint(ORANGE), band(0.0, 0.3, GUN)), up=GN(hatch(0.5, 0.2, 0.5, 0.35, handle=False)),
          down=F(paint(C('#D5D9DE')), leds(0.5, 0.5, 4, True)))
    # front wall of the cab: pillars, dado, header, two windscreens
    b.box(0.2, 1.18, 8.4, 2.8, 1.8, 8.5, all=wall(), front=wall(), back=inn)
    b.box(0.2, 2.85, 8.4, 2.8, 3.05, 8.5, all=wall(), front=wall(band(0.0, 0.3, GUN)), back=inn)
    for xa, xb in ((0.2, 0.35), (1.4, 1.6), (2.65, 2.8)):
        b.box(xa, 1.8, 8.4, xb, 2.85, 8.5, all=wall(), front=wall(), back=inn)
    for xa, xb in ((0.35, 1.4), (1.6, 2.65)):
        b.box(xa, 1.8, 8.44, xb, 2.85, 8.48, all=GN(), front=F(windshield(False)), back=F(windshield(False)),
              flags=['glow'], active={'front': F(windshield(True)), 'back': F(windshield(True))})
    # stepped nose: lower apron with headlamps + number plate, sun visor
    b.box(0.32, 1.4, 8.5, 2.68, 1.95, 8.62, all=F(paint(ORANGE), band(0.0, 0.2, GUN)),
          front=F(paint(ORANGE), hband(0.0, 0.3, 0.1), text(0.5, 0.62, 'LOCO-01', WHITE, 0.3, plate=DARK2), logo(0.5, 0.3, 0.5)) if False else
          F(paint(ORANGE), hband(0.8, 1.0, 0.09), text(0.5, 0.42, 'LOCO-01', WHITE, 0.3, plate=DARK2)),
          up=GN())
    b.box(0.2, 2.98, 8.5, 2.8, 3.05, 8.7, all=F(paint(GUN), band(0.0, 0.25, ORANGE)), front=F(paint(GUN), hband(0.0, 1.0, 0.07)))
    for xc in (0.62, 2.38):
        b.box(xc - 0.17, 1.45, 8.62, xc + 0.17, 1.88, 8.68, share='headlamp', all=GN(), front=lens(C('#FFF4D0'), True), flags=['alwaysGlow'])
        b.box(xc - 0.06, 3.15, 8.5, xc + 0.06, 3.22, 8.58, share='marker', all=GN(), front=lens(C('#FFF4D0'), True), flags=['alwaysGlow'])
    for xc in (0.62, 2.38):
        b.box(xc - 0.13, 1.35, 0.42, xc + 0.13, 1.6, 0.5, share='taillamp', all=GN(), back=lens(C('#FF5A4A'), False),
              flags=['glow'], active={'back': lens(C('#FF5A4A'), True)})
    # ---- console + seats inside the cab
    b.box(0.6, 1.26, 8.0, 2.4, 1.72, 8.4, all=F(paint(GUN), band(0.0, 0.15, YELLOW)),
          back=F(paint(GUN), console(0.5, 0.45, 1.6, 0.34, on=False, kind='bars', seed=71)),
          active={'back': F(paint(GUN), console(0.5, 0.45, 1.6, 0.34, on=True, kind='bars', seed=71))})
    b.box(0.6, 1.72, 8.05, 2.4, 1.8, 8.4, all=GN(),
          up=F(solid(C('#101820')), screen_d(0.2, 0.5, 0.28, 0.7, 'graph', False, 72), screen_d(0.5, 0.5, 0.28, 0.7, 'bars', False, 73), screen_d(0.8, 0.5, 0.28, 0.7, 'text', False, 74)),
          flags=['glow'],
          active={'up': F(solid(C('#101820')), screen_d(0.2, 0.5, 0.28, 0.7, 'graph', True, 72), screen_d(0.5, 0.5, 0.28, 0.7, 'bars', True, 73), screen_d(0.8, 0.5, 0.28, 0.7, 'text', True, 74))})
    # Two seats near the rear wall of the cab with leg room in front (the rider sits on the right one, x = 2.0: cushion top
    # y = 1.56, hips at z = 6.85, see TrainRide.SEAT_*). A base column, armrests and a headrest make them look like real chairs.
    for xc in (1.0, 2.0):
        b.box(xc - 0.06, 1.26, 6.8, xc + 0.06, 1.42, 6.95, share='seatbase', all=F(solid(GUN)))
        b.box(xc - 0.22, 1.42, 6.65, xc + 0.22, 1.56, 7.1, share='seat', all=F(seat()), up=F(seat(C('#3B5672'))))
        b.box(xc - 0.22, 1.56, 6.55, xc + 0.22, 2.1, 6.65, share='seatback', all=F(seat()), front=F(seat(C('#3B5672'))))
        b.box(xc - 0.13, 2.1, 6.55, xc + 0.13, 2.32, 6.65, share='headrest', all=F(seat()), front=F(seat(C('#3B5672'))))
        for side in (-1, 1):
            b.box(xc + side * 0.22 - 0.03, 1.56, 6.7, xc + side * 0.22 + 0.03, 1.66, 7.05, share='armrest', all=F(solid(GUN)))
    b.box(1.25, 2.98, 7.3, 1.75, 3.05, 7.7, share='cablamp', all=GN(), down=lens(C('#FFF0B0'), False), flags=['glow'],
          active={'down': lens(C('#FFF0B0'), True)})
    # cab roof kit: horn + aircon
    b.box(1.4, 3.15, 6.9, 1.6, 3.32, 7.1, all=F(cylinder(STEEL_L, 'y', rings=0)), share='horn')
    b.box(0.7, 3.15, 6.5, 2.3, 3.3, 7.6, all=F(paint(GUN), band(0.0, 0.3, ORANGE)), up=GN(vent(0.5, 0.5, 0.8, 0.8)))
    handrails(b, 0.7, 6.0, 1.72, step=1.1, tag='hr_loco')
    for xa, xb in ((0.1, 0.2), (2.8, 2.9)):
        b.box(xa, 1.1, 0.5, xb, 1.18, 6.2, share='walkway', all=GN(hband(0.0, 1.0, 0.07)), up=GRATE)
    for xa, xb in ((0.105, 0.195), (2.805, 2.895)):
        b.box(xa, 2.45, 8.3, xb, 2.5, 8.4, share='mirror_arm', all=F(solid(GUN)))
        b.box(xa, 2.3, 8.32, xb, 2.65, 8.48, share='mirror', all=F(solid(GUN)), front=F(pane(C('#9CC8E0'), 1)))
    b.particle = sh.get('particle_loco', F(paint(ORANGE), logo(0.5, 0.5, 1.0)), 1.0, 1.0)
    validate_vehicle(b, L)
    b.export()


def chassis(b, L, z0=0.5, z1=None, colour=C('#3A3F46')):
    """Common wagon underframe: frame, centre sill, air reservoir, deck plate, buffer beams + couplers."""
    z1 = L - 0.5 if z1 is None else z1
    b.box(0.25, 0.98, z0, 2.75, 1.14, z1, all=F(paint(GUN), band(0.55, 1.0, ORANGE_D)), up=F(floor(C('#5C6167'))))
    b.box(1.1, 0.88, z0, 1.9, 0.98, z1, all=GN(hband(0.0, 1.0, 0.07)))
    tube(b, 'z', 1.5, 0.72, 0.15, (z0 + z1) / 2 - 0.7, (z0 + z1) / 2 + 0.7, STEEL_D, steps=2, bands=[((z0 + z1) / 2 - 0.55, (z0 + z1) / 2 - 0.45, YELLOW)],
         share='reservoir')
    b.box(0.2, 1.14, z0, 2.8, 1.24, z1, all=GN(hband(0.0, 1.0, 0.07)), up=F(floor(C('#666B71')), hband(0.0, 0.02), hband(0.98, 1.0)))
    end_gear(b, z1, +1, L)
    end_gear(b, z0, -1, 0.0)


def ladder_box(b, x0, x1, y0, y1, z0, z1, tag):
    b.box(x0, y0, z0, x1, y1, z1, share=tag, all=F(solid(DARK)), front=F(rungs(0.5, 0.8)), back=F(rungs(0.5, 0.8)))


# =================================================================================================================
# B2) freight_car - container wagon
# =================================================================================================================
def freight_car(st, sh):
    L = 8.0
    b = newb(st, sh, 'freight_car', 4, kind='vehicles', w=3, d=int(L), ax=1, az=0)
    for zc in (1.75, 6.25):
        bogie(b, zc, motors=False)
    chassis(b, L)
    # ---- container body
    cx0, cx1, cy0, cy1, cz0, cz1 = 0.3, 2.7, 1.3, 3.3, 0.55, 7.45
    box = lambda *d: F(corrugated(ORANGE), *d)
    b.box(cx0, cy0, cz0, cx1, cy1, cz1, all=box(),
          left=box(logo(zu('left', 0.13), 0.3, 1.0), text(zu('left', 0.13), 0.62, 'FREIGHT', WHITE, 0.2), warn(zu('left', 0.92), 0.4, 0.3),
                   text(zu('left', 0.88), 0.7, 'NO. 0417', WHITE, 0.12), label(zu('left', 0.05), 0.85, 0.2)),
          right=box(logo(zu('right', 0.13), 0.3, 1.0), text(zu('right', 0.13), 0.62, 'FREIGHT', WHITE, 0.2), warn(zu('right', 0.92), 0.4, 0.3),
                    text(zu('right', 0.88), 0.7, 'NO. 0417', WHITE, 0.12), label(zu('right', 0.05), 0.85, 0.2)),
          front=box(text(0.5, 0.3, 'FICSIT', WHITE, 0.3), warn(0.5, 0.72, 0.3), hband(0.9, 1.0, 0.08)),
          back=box(text(0.5, 0.3, 'FICSIT', WHITE, 0.3), warn(0.5, 0.72, 0.3), hband(0.9, 1.0, 0.08)),
          up=box(hband(0.0, 0.04, 0.07), hband(0.96, 1.0, 0.07)))
    # sliding cargo doors (overlay on each flank) with lock rods + running rail
    for side in ('L', 'R'):
        S = Side(b, side, VW)
        door = lambda f: F(corrugated(C('#8F969E')), custom(_container_doors), hband(0.94, 1.0, 0.07))
        S.box(0.26, 1.42, 2.4, 0.3, 3.18, 5.6, all=GN(), outer=door, inner=F(paint(GUN)), share='cargo_door' + side)
        S.box(0.2, 3.18, 2.2, 0.3, 3.26, 5.8, share='door_rail', all=GN(hband(0.0, 1.0, 0.07)), up=GRATE)
        for zz in (2.2, 5.6):
            S.box(0.22, 1.32, zz, 0.3, 1.42, zz + 0.2, share='door_guide', all=F(solid(STEEL_D)))
    # corner castings + twist locks
    for x0, x1 in ((0.24, 0.42), (2.58, 2.76)):
        for y0, y1 in ((1.26, 1.44), (3.16, 3.34)):
            for z0, z1 in ((0.5, 0.68), (7.32, 7.5)):
                b.box(x0, y0, z0, x1, y1, z1, share='casting', all=F(paint(GUN, rivets=False)), up=F(solid(STEEL_D)))
    # roof ridge + hatch
    b.box(0.8, 3.3, 0.9, 2.2, 3.4, 7.1, all=F(paint(ORANGE_D), band(0.0, 0.3, GUN)),
          up=F(paint(ORANGE), hatch(0.5, 0.2, 0.6, 0.12, handle=False), hatch(0.5, 0.8, 0.6, 0.12, handle=False), vent(0.5, 0.5, 0.3, 0.1),
               text(0.5, 0.5, 'FICSIT', WHITE, 0.12)))
    # end ladders (both ends)
    for xa, xb in ((0.42, 0.66), (2.34, 2.58)):
        ladder_box(b, xa, xb, 1.3, 3.3, 0.5, 0.55, 'ladderB')
        ladder_box(b, xa, xb, 1.3, 3.3, 7.45, 7.5, 'ladderF')
    handrails(b, 0.9, 7.1, 1.55, step=1.4, tag='hr_frt', y_base=1.24, xs=((0.1, 0.14), (2.86, 2.9)))
    b.particle = sh.get('particle_frt', F(corrugated(ORANGE)), 1.0, 1.0)
    validate_vehicle(b, L)
    b.export()


# =================================================================================================================
# B3) fluid_freight_car - tank wagon
# =================================================================================================================
def fluid_freight_car(st, sh):
    L = 8.0
    b = newb(st, sh, 'fluid_freight_car', 4, kind='vehicles', w=3, d=int(L), ax=1, az=0)
    for zc in (1.75, 6.25):
        bogie(b, zc, motors=False)
    chassis(b, L)
    cy, R = 2.24, 1.1
    # saddles/cradles under the tank
    for zc in (1.75, 6.25):
        b.box(0.5, 1.24, zc - 0.2, 2.5, 1.45, zc + 0.2, share='saddle', all=F(paint(GUN), band(0.0, 0.3, YELLOW)))
    decor = lambda lvl, face: (
        [logo(zu(face, 0.2), 0.5, 1.15), text(zu(face, 0.52), 0.34, 'FLUID', BLUE_D, 0.26), text(zu(face, 0.52), 0.74, 'FICSIT', DARK2, 0.14),
         warn(zu(face, 0.86), 0.5, 0.32), text(zu(face, 0.08), 0.5, '07', DARK2, 0.2)]
        if lvl == 0 and face in ('left', 'right') else
        ([hband(0.0, 1.0, 0.08)] if lvl != 0 and face in ('up',) and False else []))
    tube(b, 'z', 1.5, cy, R, 0.95, 7.05, WHITE,
         bands=[(1.3, 1.6, BLUE), (3.55, 3.75, BLUE), (4.25, 4.45, BLUE), (6.4, 6.7, BLUE)],
         seams=[2.25, 3.15, 4.85, 5.75], decor=decor, share='tank')
    for z0, z1, c0, c1 in ((0.62, 0.95, 'manway', 'plain'), (7.05, 7.38, 'plain', 'manway')):
        tube(b, 'z', 1.5, cy, 0.93, z0, z1, OFFWHITE, bands=[(z0, z1, BLUE_D) if False else (z0 + 0.12, z0 + 0.2, BLUE)], cap0=c0, cap1=c1,
             share='head' + c0)
    # dome hatch + vent stack, catwalk on top
    tube(b, 'y', 1.5, 4.0, 0.42, cy + R - 0.02, cy + R + 0.1, STEEL, bands=[(cy + R + 0.03, cy + R + 0.07, YELLOW)], cap1='manway', share='dome')
    b.box(1.3, cy + R, 1.0, 1.7, cy + R + 0.05, 3.5, share='catwalk', all=GN(hband(0.0, 1.0, 0.07)), up=GRATE)
    b.box(1.3, cy + R, 4.5, 1.7, cy + R + 0.05, 7.0, share='catwalk', all=GN(hband(0.0, 1.0, 0.07)), up=GRATE)
    tube(b, 'y', 0.95, 3.0, 0.07, cy + R - 0.02, cy + R + 0.2, STEEL_L, steps=1, share='vent1')
    # end access ladders on both heads
    ladder_box(b, 1.25, 1.75, 1.24, cy + R, 0.55, 0.6, 'fl_ladderB')
    ladder_box(b, 1.25, 1.75, 1.24, cy + R, 7.4, 7.45, 'fl_ladderF')
    # pipe manifold beneath the tank with valves + blue outlet stubs on both flanks
    tube(b, 'x', 4.0, 0.7, 0.1, 0.35, 2.65, STEEL, bands=[(1.3, 1.7, YELLOW)], steps=1, share='manifold')
    for xc in (0.65, 2.35):
        b.box(xc - 0.11, 0.55, 3.86, xc + 0.11, 0.85, 4.14, share='valveblk', all=F(paint(GUN), band(0.0, 0.25, YELLOW)))
        b.box(xc - 0.09, 0.85, 3.9, xc + 0.09, 0.9, 4.1, share='valvewheel', all=F(paint(RED), ring(0.5, 0.5, 0.35, BLACK, 0.12)))
    tube(b, 'x', 4.0, 0.7, 0.13, 0.12, 0.35, BLUE, bands=[(0.12, 0.18, STEEL_L)], steps=1, cap0='pipe', share='outletL')
    tube(b, 'x', 4.0, 0.7, 0.13, 2.65, 2.88, BLUE, bands=[(2.82, 2.88, STEEL_L)], steps=1, cap1='pipe', share='outletR')
    handrails(b, 0.9, 7.1, 1.55, step=1.4, tag='hr_fl', y_base=1.24, xs=((0.1, 0.14), (2.86, 2.9)))
    b.particle = sh.get('particle_fl', F(paint(WHITE), band(0.4, 0.6, BLUE)), 1.0, 1.0)
    validate_vehicle(b, L)
    b.export()


# =================================================================================================================
# C) trackside models: signals, switch stand, switch lever  (X, Z in 0..1, front = z max)
# =================================================================================================================
def validate_small(b, ymax):
    for i, p in enumerate(b.parts):
        (x0, y0, z0), (x1, y1, z1) = p['from'], p['to']
        if min(x0, y0, z0) < -1e-6 or x1 > 1 + 1e-6 or z1 > 1 + 1e-6 or y1 > ymax:
            raise SystemExit('%s: part %d out of bounds %s %s' % (b.name, i, p['from'], p['to']))
    # the two lamp volumes must stay empty
    if b.name.startswith('rail_signal'):
        for i, p in enumerate(b.parts):
            (x0, y0, z0), (x1, y1, z1) = p['from'], p['to']
            for (ly0, ly1) in ((3.55, 3.89), (3.11, 3.45)):
                if x0 < 0.67 and x1 > 0.33 and y0 < ly1 and y1 > ly0 and z0 < 0.79 and z1 > 0.75:
                    raise SystemExit('%s: part %d intrudes into a lamp volume' % (b.name, i))


def signal(st, sh, kind):
    """kind 'block' -> orange housing + black B plate;  'path' -> white housing + yellow hazard band + P plate."""
    blk = kind == 'block'
    name = 'rail_signal_' + kind
    b = newb(st, sh, name, 5, kind='vehicles', w=1, d=1, ax=0, az=0, geo_name='signal_' + kind)
    body_c = ORANGE if blk else WHITE
    paint_body = lambda *d: F(paint(body_c), *d)
    post = lambda *d: F(strut(C('#8C939B') if blk else C('#B8BEC5'), band=YELLOW), *d)
    # foundation + hazard plinth
    b.box(0.2, 0.0, 0.2, 0.8, 0.12, 0.8, all=HAZ, up=F(floor(C('#6A6F75'))))
    # relay cabinet at the foot of the post
    b.box(0.62, 0.12, 0.42, 0.86, 0.95, 0.72, all=paint_body(band(0.0, 0.1, GUN)),
          front=paint_body(band(0.0, 0.1, GUN), warn(0.5, 0.35, 0.34), label(0.5, 0.75, 0.5)),
          right=paint_body(band(0.0, 0.1, GUN), text(0.5, 0.5, 'B' if blk else 'P', DARK, 0.5, plate=WHITE if blk else YELLOW)),
          left=paint_body(band(0.0, 0.1, GUN)), up=GN())
    # 0.3 wide post
    b.box(0.35, 0.12, 0.4, 0.65, 2.9, 0.7, all=post(), up=GN())
    # letter plate on the post front
    if blk:
        b.box(0.37, 1.75, 0.7, 0.63, 2.45, 0.725, all=GN(), front=F(paint(BLACK), text(0.5, 0.5, 'B', WHITE, 0.4), frame_fn(WHITE)))
    else:
        b.box(0.37, 1.75, 0.7, 0.63, 2.45, 0.725, all=GN(), front=F(paint(YELLOW), text(0.5, 0.5, 'P', BLACK, 0.4), frame_fn(BLACK)))
    # signal head: dark front panel, coloured shell
    face = F(solid(C('#191B1F')), ring(0.5, 0.317, 0.205, STEEL_D, 0.02), ring(0.5, 0.683, 0.205, STEEL_D, 0.02),
             rect_hazard(), bolts_edge(0.1, 0.4), text(0.14, 0.5, '1', ORANGE_L, 0.1), text(0.86, 0.5, '2', ORANGE_L, 0.1))
    side_plate = lambda f: paint_body(band(0.0, 0.08, GUN), text(0.5, 0.42, 'B' if blk else 'P', DARK if blk else DARK,
                                                                  0.36, plate=WHITE if blk else YELLOW), hband(0.9, 1.0, 0.09))
    b.box(0.15, 2.9, 0.35, 0.85, 4.1, 0.75, all=paint_body(band(0.0, 0.06, GUN)), front=face, left=side_plate('left'), right=side_plate('right'),
          back=paint_body(band(0.0, 0.06, GUN), label(0.5, 0.55, 0.4), warn(0.5, 0.22, 0.25)),
          up=GN(vent(0.5, 0.5, 0.4, 0.2)))
    # lamp shrouds: cheeks + visors (lamp volumes x .33-.67, y 3.11-3.45 / 3.55-3.89, z .75-.79 stay empty)
    for xa, xb in ((0.285, 0.32), (0.68, 0.715)):
        b.box(xa, 3.04, 0.75, xb, 3.95, 0.85, share='cheek', all=F(solid(C('#15171A'))))
    for y0, y1 in ((3.9, 3.96), (3.46, 3.52)):
        b.box(0.27, y0, 0.75, 0.73, y1, 0.9, share='visor', all=F(solid(C('#15171A'))), up=F(solid(C('#15171A')), hband(0.0, 1.0, 0.06)))
    b.box(0.27, 3.02, 0.75, 0.73, 3.09, 0.84, share='sill', all=F(solid(C('#15171A'))))
    # cap, antenna, hazard band
    b.box(0.12, 4.1, 0.32, 0.88, 4.17, 0.78, all=F(paint(GUN), band(0.0, 0.3, body_c)), up=GN(hband(0.0, 1.0, 0.08)))
    b.box(0.475, 4.17, 0.535, 0.525, 4.38, 0.585, share='mast', all=F(cylinder(STEEL_L, 'y', rings=0)))
    b.box(0.45, 4.34, 0.51, 0.55, 4.4, 0.61, share='mastball', all=F(solid(RED)), flags=['alwaysGlow'])
    if not blk:
        # path signals carry an extra yellow route lamp box on the left of the head
        b.box(0.06, 3.3, 0.45, 0.15, 3.7, 0.65, all=F(paint(YELLOW), hband(0.0, 0.3, 0.08)), left=F(paint(YELLOW), text(0.5, 0.5, 'P', BLACK, 0.3)))
    b.particle = sh.get('particle_' + name, F(paint(body_c), band(0.4, 0.6, YELLOW)), 1.0, 1.0)
    validate_small(b, 4.45)
    b.export()


def frame_fn(c):
    def fn(cv):
        cv.frame(1, 1, cv.W - 1, cv.H - 1, c, 1)
    return fn


def rect_hazard():
    def fn(cv):
        cv.frame(0, 0, cv.W, cv.H, STEEL_D, 1)
    return fn


def switch_stand(st, sh):
    b = newb(st, sh, 'switch_stand', 2, kind='vehicles', w=1, d=1, ax=0, az=0)
    b.item = False
    b.box(0.12, 0.0, 0.12, 0.88, 0.1, 0.88, all=HAZ, up=F(floor(C('#6A6F75'))))
    ped = lambda *d: OR(band(0.0, 0.12, GUN), *d)
    b.box(0.2, 0.1, 0.2, 0.8, 0.9, 0.8, all=ped(hband(0.55, 0.68, 0.07)),
          front=ped(hband(0.55, 0.68, 0.07), text(0.5, 0.22, 'SWITCH', WHITE, 0.1), label(0.5, 0.8, 0.3), warn(0.5, 0.42, 0.14)),
          back=ped(hband(0.55, 0.68, 0.07), vent(0.5, 0.3, 0.3, 0.3)),
          left=ped(hband(0.55, 0.68, 0.07), vent(0.5, 0.3, 0.3, 0.3)), right=ped(hband(0.55, 0.68, 0.07), vent(0.5, 0.3, 0.3, 0.3)),
          up=GN())
    # indicator head with a lit plate (arrows for both routes, lit while powered)
    ind = lambda on: F(solid(C('#14181C')), custom(_indicator(on)))
    b.box(0.24, 0.9, 0.3, 0.76, 1.1, 0.7, all=F(paint(GUN), band(0.0, 0.2, YELLOW)), front=ind(True), back=ind(True),
          left=F(paint(GUN), hband(0.0, 1.0, 0.09)), right=F(paint(GUN), hband(0.0, 1.0, 0.09)), up=F(solid(STEEL_D)),
          flags=['alwaysGlow'])
    b.box(0.4, 1.1, 0.4, 0.6, 1.13, 0.6, share='boss', all=F(cylinder(STEEL_L, 'y', rings=0)))
    b.particle = sh.get('particle_sw', F(paint(ORANGE), hband(0.5, 0.7)), 1.0, 1.0)
    validate_small(b, 1.15)
    b.export()


def _indicator(on):
    def fn(cv):
        cv.fill(C('#0C1014'))
        W, H = cv.W, cv.H
        cv.frame(0, 0, W, H, STEEL_D, 1)
        # left arrow (green: straight) and right arrow (amber: diverging)
        for (cx, col, d) in ((0.27, GREEN, -1), (0.73, C('#FFB03A'), 1)):
            c = col if on else col * 0.3
            x = int(cx * W)
            y = H // 2
            hh = max(2, H // 3)
            for k in range(hh):
                cv.rect(x - d * (hh // 2) + d * k, y - (hh - k) // 1 // 2, x - d * (hh // 2) + d * k + 1, y + (hh - k) // 2 + 1, c)
            cv.rect(x + d * 1, y - 1, x + d * (hh // 2 + 3), y + 1, c)
        cv.clean[:] = 1 if on else 0
    return fn


def switch_lever(st, sh):
    b = newb(st, sh, 'switch_lever', 2, kind='vehicles', w=1, d=1, ax=0, az=0)
    b.item = False
    b.box(0.41, 0.0, 0.41, 0.59, 0.1, 0.59, all=F(paint(GUN)), up=F(solid(STEEL_D)))
    b.box(0.465, 0.1, 0.465, 0.535, 0.82, 0.535, all=F(cylinder(STEEL_L, 'y', rings=0), hband(0.0, 0.14, 0.05)))
    b.box(0.43, 0.14, 0.43, 0.57, 0.24, 0.57, all=F(paint(YELLOW), band(0.4, 0.6, BLACK)))
    b.box(0.4, 0.82, 0.4, 0.6, 1.0, 0.6, all=F(paint(ORANGE), band(0.0, 0.2, GUN)), up=F(solid(ORANGE_L)))
    b.particle = sh.get('particle_lv', F(paint(ORANGE)), 1.0, 1.0)
    validate_small(b, 1.05)
    b.export()


def main():
    if os.path.isdir(TRN):
        shutil.rmtree(TRN)
    for d in (TRN, GEO_B, GEO_V, ITEM_MODELS, ITEM_TEX):
        os.makedirs(d, exist_ok=True)
    gen_lamps()
    gen_track_ballast()
    gen_track_sleeper()
    gen_track_rail()
    gen_track_hologram()
    gen_railway_icon()
    st = TStore(TRN)
    sh = Shared(st)
    DOWN_ID[0] = sh.get('under', F(solid(DARK)), 1, 1, 'down')
    empty_platform(st, sh)
    train_station(st, sh)
    freight_platform(st, sh)
    fluid_freight_platform(st, sh)
    locomotive(st, sh)
    freight_car(st, sh)
    fluid_freight_car(st, sh)
    signal(st, sh, 'block')
    signal(st, sh, 'path')
    switch_stand(st, sh)
    switch_lever(st, sh)
    summary(st)


def summary(st):
    print('FICSIT Craft train art - files written')
    print('-' * 118)
    for p, note in WRITTEN:
        print('%-92s %s' % (p, note))
    n_png = sum(len(fs) for _, _, fs in os.walk(TRN))
    print('-' * 118)
    print('%s: %d PNG files (%d unique per-face textures incl. %d shared parts textures + track/lamp textures)'
          % (relp(TRN), n_png, st.count, len(os.listdir(os.path.join(TRN, 'shared'))) if os.path.isdir(os.path.join(TRN, 'shared')) else 0))
    print('geometry: %d building + %d vehicle JSON files, %d item models'
          % (sum(1 for p, _ in WRITTEN if '/buildings/' in p), sum(1 for p, _ in WRITTEN if '/vehicles/' in p),
             sum(1 for p, _ in WRITTEN if '/models/item/' in p)))


if __name__ == '__main__':
    main()
    import squarify  # block-atlas textures must be square (see squarify.py)
    squarify.main()
